### ISSUE TITLE
Delegate Project Relationship Management for each Project

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#104]

**Comment by jessicazartler** [comment]
📋 Anything to add?
https://deepdao.io/#/deepdao/dashboard
Once token is live

🎉 Subtasks
[ ]
[ ]
[ ]
🤼‍♂️ Reviewer
@

🔗 Work doc - inspirational links

**Comment by eduardovegap** [comment]
Has this document been open to the rest of the community in order for people to propose/submit/apply?

**Comment by jessicazartler** [comment]
No not yet, let's discuss as it has emails we were keeping the doc permissioned

**Comment by tamarandom** [comment]
As we're doing this now in our Onboarding weekly calls with the new xls, closing!
