### ISSUE TITLE
Proposal / TE HG2TG Book 

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#105]

**Comment by tamarandom** [comment]
Hey @jessicazartler ! Are you the person to own this? @eduardovegap and I are using the same assignments as were on the tec_curate xls but things may have shifted.

**Comment by jessicazartler** [comment]
Asked Sebnem for a final answer if she will submit or decided no.. will circle back soon and update

**Comment by jessicazartler** [comment]
Dup #342
