### ISSUE TITLE
Run an AMA for Proposals

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#108]

**Comment by jessicazartler** [comment]
📋 Anything to add?

🎉 Subtasks
[ ] Collect questions & 
[ ] Promote AMA via Meetup, in channels one week before and day before Tweet etc.
[ ] Host AMA for how to submit proposals LIVE on YouTube
[ ] Post distribution and outreach

🤼‍♂️ Reviewer
@eduardovegap @jessicazartler 

🔗 Work doc - inspirational links

**Comment by drllau** [comment]
This may be a little premature until get the legal risks worked out for the proposal submission / qualification / acceptance process. For example, can you "promise" anything without the source of funds/donations identified?

**Comment by jessicazartler** [comment]
Absolutely thank you! Won't run until we get clarity, just filing for when we get there - appreciate all of your comments and guidance Dr. Lau!

**Comment by eduardovegap** [comment]
@liviade1 can we change the name of this to AMA and place the link for wednesday call? 

@tamarandom we can make it recurrent.

**Comment by tamarandom** [comment]
Good idea, @eduardovegap ! The outreach to proposals should be of interest for the new community members too. I can see one AMA serve both purposes. @liviade1 does this make sense to you too? Or maybe there are reasons to have a separate one?

**Comment by tamarandom** [comment]
Update : Closed!
