### ISSUE TITLE
Garden Swarm : Hatch website 

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#112]
## 📋   Anything to add?

More details about this on the Garden Swarm project page: 

--> https://github.com/orgs/TECommons/projects <--

## 🎉   Subtasks

- [ ] front-end
- [ ] TEC UI 
- [ ] subgraph

## 🤼‍♂️   Reviewer

@

**Comment by iviangita** [comment]
Copied and moved to Gardens Swarm Workspace [issue 21](https://app.zenhub.com/workspaces/garden-swarm-workspace-5fe322aef3aab0001be1d518/issues/tecommons/tec-ui/21)
