### ISSUE TITLE
Finish Smart Contracts

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#113]
## 📋   Anything to add?

More details on Garden Swarm's project board:
https://github.com/orgs/TECommons/projects/1

## 🎉   Subtasks

- [x] Bonding Curve
- [ ] Hatch
- [ ] Conviction Voting
- [ ] Dandelion

## 🤼‍♂️   Reviewer

@

**Comment by iviangita** [comment]
Copied and moved to Gardens Swarm workspace [issue 22](https://app.zenhub.com/workspaces/garden-swarm-workspace-5fe322aef3aab0001be1d518/issues/tecommons/tec-ui/22)
