### ISSUE TITLE
Review Smart Contracts

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#114]
## 📋   Anything to add?
More details on Garden Swarm board:
https://github.com/orgs/TECommons/projects/1

## 🎉   Subtasks

- [ ] Conviction Voting
- [ ] Hatch
- [ ] Tollgate + Hooked Dandelion Voting
- [ ] Market Maker (bonding curve)

## 🤼‍♂️   Reviewer

@

**Comment by iviangita** [comment]
Copied and moved to Gardens Swarm Workspace [issue 23](https://app.zenhub.com/workspaces/garden-swarm-workspace-5fe322aef3aab0001be1d518/issues/tecommons/tec-ui/23)
