### ISSUE TITLE
Conviction voting front-end

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#115]
## 📋   Anything to add?
Details on Garden Swarm board : 
https://github.com/orgs/TECommons/projects/1

## 🎉   Subtasks

- [ ] design
- [ ] implementation

## 🤼‍♂️   Reviewer

@

**Comment by iviangita** [comment]
Copied and moved to Gardens Swarm Workspace [issue 10](https://app.zenhub.com/workspaces/garden-swarm-workspace-5fe322aef3aab0001be1d518/issues/tecommons/tec-ui/10)
