### ISSUE TITLE
Hatch: Min and max goals

### ISSUE THREAD

**Issue by sembrestels** [TECommons/coordination#116]
## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by drllau** [comment]
Just observation ... if one of the judicial options post-hatch #43 is European Cooperative Society, then €30k is minimum capital requirement

**Comment by tamarandom** [comment]
Update : the param is ready. Will be deployed in the test hatch later this week. Then we can close this issue.

**Comment by GriffGreen** [comment]
Vivi is a hero
