### ISSUE TITLE
Hatch: Impact hours conversion

### ISSUE THREAD

**Issue by sembrestels** [TECommons/coordination#117]
## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by tamarandom** [comment]
Discussion on the Forum:

https://forum.tecommons.org/t/impact-hour-rewards-deep-dive/90

**Comment by tamarandom** [comment]
Update : the param is ready. Will be deployed in the test hatch later this week. Then we can close this issue.

**Comment by GriffGreen** [comment]
FABI YOU BEAST!
