### ISSUE TITLE
Finish Hatch Smart Contract

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#118]
## 🤼‍♂️   Reviewer

@

**Comment by GriffGreen** [comment]
Hatch will be separated from the marketplace app

**Comment by iviangita** [comment]
Copied and moved to Gardens Swarm Workspace [issue 11](https://app.zenhub.com/workspaces/garden-swarm-workspace-5fe322aef3aab0001be1d518/issues/tecommons/tec-ui/11)
