### ISSUE TITLE
Fix the token locking "bug" in the Dandelion Smart Contract (after hatch)

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#121]

**Comment by GriffGreen** [comment]
Fix the extra token being blocked or not?

**Comment by iviangita** [comment]
Copied and moved to Gardens Swarm Workspace [issue 14](https://app.zenhub.com/workspaces/garden-swarm-workspace-5fe322aef3aab0001be1d518/issues/tecommons/tec-ui/14)
