### ISSUE TITLE
Review Smart Contract : Conviction Voting

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#123]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by iviangita** [comment]
Copied and moved to Gardens Swarm Workspace [issue 16](https://app.zenhub.com/workspaces/garden-swarm-workspace-5fe322aef3aab0001be1d518/issues/tecommons/tec-ui/16)
