### ISSUE TITLE
Conflict manager - Suggested new role

### ISSUE THREAD

**Issue by JuankBell** [TECommons/coordination#129]
Responsibilities: to act in alignment with the TEC mission, vision, values and code of conduct. 
Commitment: of 4+ hours per week almost every week until the TE Commons (and after?) is Deployed on the functions stated below
In addition: receive cases from the conflict management requests. 

Receive cases from conflict management requests (BOT)
Apply and participate in periodical review of graduate sanctions
Up-to-date with all the decisions taken by the TEC 
Knowledge and training of scaling protocols and conflict management mechanisms 
Accountables of easy access and use of the conflict protocol 
Rotative role - Máx 2-3 years in a row
Receives Praise

Reward for contribution: earn Creds & Impact Hours Tier 1 or 2 (see section “Contribution Reward“) , gain visibility in TEC Leaderboard
Associated rights: impact TEC’s near team mission, TE Commons governance rights not defined yet, Creds & Impact Hours might be exchanged to tokens once TE Commons is launched,

**Comment by drllau** [comment]
Observation from real-life is that crime tends to be low in small communities where people generally know/recognise each other. Only in larger towns does need for specialised people (police) emerge. The only legal requirement is for a mandatory dispute resolution process for token "investors" which may not be necessary until the 2nd open phase of the hatch.

**Comment by JuankBell** [comment]
The conflict managers should not be people wanting rewards, but people interested in the wellbeing of humans/the community. Tier 2 in spiral dynamics. (is it a conflict between i/we/us/it).

**Comment by JuankBell** [comment]
Gravitons.

**Comment by tamarandom** [comment]
Add this role to the Onboarding document. Then close. ;)

**Comment by JuankBell** [comment]
added to this document:

https://docs.google.com/document/d/1UDnf26QQqqc77mnhn80MLCVzJU6IdvouT-OXPrIVXCg/edit#heading=h.tpx9g4b760ky
