### ISSUE TITLE
Conflict Mgmt Role Design

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#130]
## 📋 Anything to add?

Design the responsibilities/benefits/requirements of the role of conflict managers.

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by JuankBell** [comment]
Gravity role design forum post: https://forum.tecommons.org/t/gravity-role-design/174

Rules and boundaries are key for managing Common Pool Resources, and monitoring gives legitimacy to agreements toward maintaining trust and collective goodwill.

We are proposing a mutual-monitoring system, where each one of us can inform any issue (through the Gravity [Typeform](https://the-commons-stack.typeform.com/to/rCVsK5RK)) to a designated group of members in the community, that will assume the following **responsibilities:**

a) As individuals, to promote dialogue within the organization and manage conflicts addressed through ADR ([Alternative Dispute Resolution](https://en.wikipedia.org/wiki/Alternative_dispute_resolution)),

b) As a collective, to take decisions on the implementation of [graduated sanctions](http://patternsofcommoning.org/uncategorized/eight-design-principles-for-successful-commons/).

c) As both a collective and individuals, to commit to the practice of preventing, contextualizing and resolving disputes by regular attendance in our community practice.

**Gravity members must commit to additional exigences that are required to join and stay in the collective. Such as:**

1. Voluntary Process: All members in the Gravity group participate without coercion from any actor.

2. Self-Determination: Recognize the ability to promote voluntary agreements. The mediator facilitates the management of disputes but the outcomes belong to the parties.

3. Conflict of interest: Recognize when they are not capable of facilitating a conversation for any possible bias reason, personal or professional.

4. Competence: As we are a community of experts, the mediator, besides being trained in Alternative Dispute Resolution, should be able to prove deep understanding of the specific topics that the dispute may be about.

5. Confidentiality: Information related to these processes should be handled privately, and strategically shared with the agreement by the parties. Unwanted information filtered by the mediator is a reason to remove from the Gravity group.

6. Impartiality and neutrality: The Gravity group members should lead by their example of empathy and acceptance of different points of view, with freedom from favouritism.

7. Professional Responsibility: Gravity members should assume the task of mediating in the organization with diplomacy and prudence.

8. Rotation: Three times a year, new training and selection processes will be run to encourage members of the community to become part of the Gravity team. One can only be in this group for three years in a row, to avoid accumulation of power.

**Only a maximum of three members of the group will be able to look at the answers of the typeform** The rest of the members will participate in collective decisions for the implementation and review of graduated sanctions, communicating insights about the process, and getting assigned cases that should be accepted by the mediator to put in place.

**That implies three levels of confidentiality inside the Gravity Group,**

1. Confidentiality inside the ADR process: Information of the specific process for each case should remain exclusive to the parts involved. Only the mediator notes on a possible agreement, and the agreement will remain on the Gravity Database for follow up and accountability.

2. Gravity typeform confidentiality: Only three members of the Gravity group should be able to see the raw input that comes from the community, and their duty is to transform that input into cases that can be assigned to a gravity member to facilitate.

3. Gravity group confidentiality: discussion of cases, reviews and placement of graduate sanctions will remain as a democratic decision in the gravity group. (Still to decide voting mechanism)

Systems of Communication

+*. Each Gravity member should have Discord admin capabilities (so are we saying that Gravity has responsibility for meetings going well? If so, we need to likely extend the composition of the group to include more people with moderator abilities)
+*. Implement a [protocol](https://docs.google.com/document/d/12Pl3mpF5IautPtVdPHjh0tc8fu6JM2iTCnGyumCmULc/edit#) regarding calls:

  a). Appoint a moderator (someone who manages technically the meeting with muting powers, etc. and has to account for people’s presence in the meeting, needs technical input into the new Discord features and working group)
  b). Appoint a facilitator who manages the people in the meetings and the agenda itself. Agenda should be available to the people in the room and the moderator/facilitators prior to the meeting.

(Still to decide reward mechanism)
