### ISSUE TITLE
Setup conflict Mgmt typeform

### ISSUE THREAD

**Issue by JuankBell** [TECommons/coordination#133]
## 📋 Anything to add?

Upload the typeform for easy access of conflict mgmt,  

Setup the spreadsheet for conflict managers to review inputs from the typeform

Review proposal https://belljuancarlos.typeform.com/to/iYuhEqKY

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by tamarandom** [comment]
Closing

**Comment by JuankBell** [comment]
New link to the typeform: https://the-commons-stack.typeform.com/to/rCVsK5RK
