### ISSUE TITLE
Relate unwanted behavior to graduate sanctions

### ISSUE THREAD

**Issue by JuankBell** [TECommons/coordination#135]
Please jump into this document and help fill the space for "scale of conflicts & suggested sanctions" (It's below the main work made by soft gov & culture).

https://miro.com/app/board/o9J_kkC0kIM=/

**Comment by GriffGreen** [comment]
@liviade1 and I were talking, and in conviction voting... I am pretty sure there is a permission that allows someone the power to delete proposals.... the details we need to talk to Sem about... we will get this permission understood soon 

We need to have rules around that! And it is definitely a sanction!

I think the process should be something like... 

0. Write in the terms and conditions that people have to sign when submitting proposals the expectations of the proposals here. (these need to be clear).

.... If someone creates a proposal that doesn't match the terms and conditions
1. Private Warning, and request to remove...
..... If private conversation doesn't satisfy the conflict
2. Public post/debate (as long as the vote doesn't look like it will pass right away)
..... If public conversation doesn't satisfy the conflict, or is still on going and it looks like the vote may pass
3. Delete the proposal

**Comment by JuankBell** [comment]
The guideline for graduated sanctions and scale of conflicts was posted in the forum, https://forum.tecommons.org/t/scale-of-conflicts-graduated-sanction-guideline/234
