### ISSUE TITLE
Conflict Managers Onboarding 

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#136]
Design the onboarding/training and rotation/offboarding of this group of people related to conflict management

**Comment by JuankBell** [comment]
Conflict manager onboarding post: https://forum.tecommons.org/t/gravity-onboarding/175

Gravity Onboarding process:

An open and inclusive process will be run Three times a year to include all the interested people in the training and selection of a group of mediators in the organization, who will also facilitate and train members of the collective in the various proactive and reactive participatory activities like practice groups, forum posts and Discord channels; giving feedback on policy and procedures for the relevant working groups as needed.

What do we expect, and what is the training and selection process?

Expectation: Improve the TEC code of conduct Engage people in the Gravity Working group, relate them to its manifesto, the Soft Gov miro board, and the application of rules and sanctions according to the Gravity process.

Requirements: Assist at least to six sessions, agree to the code of conduct for mediators, show knowledge of ADR, NVC, the TEC and the Gravity process.

Postulation: All contributors in the TEC can apply to become mediators in the organization. (Still to decide)

Selection: We will try to have at least seven people (more or less the 5% of our community) trained and committed to play this role .

Training: During 4 weeks (Still to decide)

Duration: 8 hours divided into 1 hour sessions:

Study materials should be sent out before each session.

Topics:
Session 1: Theories of conflict, different perspectives
Session 2: Spiral dynamics & Nonviolent communication
Session 3: Negotiation & Alternative Dispute Resolution mechanisms
Session 4: Practical case (individual conflicts)
Session 5: Antifragility, Ostrom’s principles (CPRS)
Session 6: Code of conduct for mediators, agreements of confidentiality 
Session 7: Gravity process deep dive (forms, graduated sanctions)
Session 8: Practice case (group conflicts)

**-> If you know someone who you think would be a great facilitator on one of these topics, please reply, and also if you think there is something missing or that can be corrected.**

**Comment by JuankBell** [comment]
Training started yesterday! 21th Jan, we delivered 17 POAPs
https://poap.gallery/event/699
