### ISSUE TITLE
Parameters for conflict managing group

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#138]
## 📋   Anything to add?

Parameters for conflict managing group (ex. rotation or term limits, other things that may arise)

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Hey @JuankBell - Does this issue still need to be open?

**Comment by JuankBell** [comment]
Created three (3) new issues to keep designing parameters and planning next steps for Gravity. That enables this one to get closed. 

Survey for Conflict Management in DAOs #557 https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/tecommons/coordination/557

Gravity easy step by step process #558 https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/tecommons/coordination/558

Gravity outreach #559 https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/tecommons/coordination/559
