### ISSUE TITLE
Appointment of conflict managers

### ISSUE THREAD

**Issue by JuankBell** [TECommons/coordination#139]
## 📋 Anything to add?

How are conflict managers designated in the organization,
After training?

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by drllau** [comment]
Firstly (from a legal perspective) TEC **cannot employ** anyone
1. at the moment, legally speaking, all members of TEC involved in the hatch are members of a Swiss verein, consider it an unincorporated association with separate judicial identity
2. as such the [statutes](https://commonsstack.org/statutes) say voting members (ie those who've **paid up dues**) can put forward proposals to the assembly (all members) with simple majority
3. **after** the  hatch, you can separate into a different legal entity who then** has power to appoint whoever they wish
4. however. if it is considered **employment** there are a whole raft of labor laws to consider
5. LexDAO gets around the problem by selling ADR (alternative dispute resolution) as service hours so it is considered a subcontracting relationship

Applying systems thinking, the other approach is to measure "conflict" (however defined) and create a damping feedback loop so designated community stewards get tokens reduced for increasing conflict and praise for rapidly resoling.

**Comment by solsista** [comment]
"Applying systems thinking, the other approach is to measure "conflict" (however defined) and create a damping feedback loop so designated community stewards get tokens reduced for increasing conflict and praise for rapidly resoling." 

+ 1 

This also resembles an incentive scheme for Vibe Watchers, those who have a gift and knowledge how to resolve conflicts would naturally step in, and if they are effective, basically self-select by "righting the ship"

**Comment by JuankBell** [comment]
The appointment of the Gravitons is based on presenting the 6 POAPs related to the training sessions. That would allow people to have the support from Gravity to mediate in conflicts at their organizations.
