### ISSUE TITLE
Content for front end of Hatch app

### ISSUE THREAD

**Issue by jessicazartler** [TECommons/coordination#148]

**Comment by tamarandom** [comment]
+ @markoprljic to refine this issue and assignee to a single person.

**Comment by jessicazartler** [comment]
@sembrestels when do you need this by? Or can you let me know when the interface is fully ready? Thanks!

**Comment by markoprljic** [comment]
This issue needs better description and provide more context.

**Comment by jessicazartler** [comment]
![image](https://user-images.githubusercontent.com/43972522/107070927-f90a3480-67b1-11eb-8082-daebf3c72157.png)

Content for this ☝️

**Comment by jessicazartler** [comment]
@sembrestels let us know when you need this and deadline :D Thank you!

**Comment by markoprljic** [comment]
I think we said ther won't be any content needed here. Closing it.

**Comment by tamarandom** [comment]
For the video part, I don't see any reason not to keep an issue open "for contributors". @sembrestels was really keen on the idea of having this and while it should not block the Hatch it would be a "nice to have" if someone in the community wants to champion it. I wouldn't be surprised if @mount-manu was interested. 

The scope does not have to be a big production. 

For the rest of the content of the page, I leave that to you.

What do you think @markoprljic ?

**Comment by markoprljic** [comment]
I think this issue relates to the content that goes below the video in the screenshot above.

**Comment by tamarandom** [comment]
I did too, at first. Then I thought it probably is the content for that entire front page. Unless we already have an issue open for that? 

For the video : any reason **not** to leave this issue open "for contributors" so if there is someone in the community that wants to champion it, they can?

**Comment by markoprljic** [comment]
In any case, it needs a clear task description in order for anyone to start working in it.

**Comment by mount-manu** [comment]
Unsurprisingly, I _am_ interested in committing to this. And yes, I'd appreciate a clear task description (and, if applicable, an expected date of completion so that I can prioritize this accordingly among the other video production tasks I'm already working on).

**Comment by markoprljic** [comment]
Great! 
@jessicazartler can you please provide descriptive instructions for this issue and reopen it?

Thanks.

**Comment by jessicazartler** [comment]
Yes, @markoprljic it was intended for the content that goes below the video in the screenshot above. I was looking for some guidance from @sembrestels for if and when we still need this - I would imagine we at least need a review of that content. I will write a brief description and we just need to check with Sem where this is at @tamarandom - thanks guys!
