### ISSUE TITLE
TL;DR of the Hatch Parameters Rough Draft ready for feedback

### ISSUE THREAD

**Issue by jessicazartler** [TECommons/coordination#149]
## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by GriffGreen** [comment]
with sebnem!

**Comment by freedumbs00** [comment]
https://docs.google.com/document/d/1d-7wh8oBHxL8i2A-Ofapp1zJlgP-gjyIz6REVviQzgg/edit?usp=sharing

What do you think @jessicazartler

**Comment by markoprljic** [comment]
@freedumbs00 So I've been having a discussion with Jeff in this issue https://github.com/TECommons/Token-Log-Hatch-Params/issues/56#issuecomment-790034354 and he hacked on your doc here https://docs.google.com/document/d/1rNE37FvYxkNSbIRvYXTQlOReJzXExUq_IDYv4Oem4NE/edit

Let me know if this helps.

**Comment by freedumbs00** [comment]
@markoprljic    This has now been taken care of by @divine-comedian with his TL/DR for the Hatch.  I don't think that original doc. will even be used for anything now.   As this was for a rough draft and Mitch has ready for publication I'm closing this issue.

**Comment by jessicazartler** [comment]
Just to bring some context - there is the work that is being done for TEC - which is kind of like the Alpha of the dashboard -- this will be iterated on/documented/refined/used for the rest of the ecosystem when the Commons Stack takes forward further documentation and potential network collaborations to iterate on these designs. Right now, this was built specifically for our use case, but the template will be more generalized and needs more context/documentation for other DAOs/projects to apply this code and use it later on.

The Commons Stack will be documenting this work and potentially getting funding/network collab going and will be adding documentation to the CS library.

Noting here, as well all the docs that exist on this topic for reference, and I think it would be great to use Jeff's doc going forward so might be great to all work from one doc and integrate all of the knowledge in Jake's:

Filing here for now... I will be setting up a call with Mitch about something else so will sync on this.. but also it might be good to pull in Comms people when it comes to naming params - especially Jeff :D

JAKE DOCS
https://docs.google.com/document/d/1nbHlb28-fnWQtPz-txVOVL70g5R2grzIh3bMWjjeGa8/edit#heading=h.6bc6e5a12ww9
https://docs.google.com/spreadsheets/d/1NBizA4mbj4iFuTkcfg3M1Q7v-9exhMcja8u2BshV5V8/edit#gid=0
https://docs.google.com/document/d/1d-7wh8oBHxL8i2A-Ofapp1zJlgP-gjyIz6REVviQzgg/edit

JEFF
https://docs.google.com/document/d/1rNE37FvYxkNSbIRvYXTQlOReJzXExUq_IDYv4Oem4NE/edit

**Comment by markoprljic** [comment]
Thanks @jessicazartler 
For the Param Glossary let's go on with [Jeff's doc. ](https://docs.google.com/document/d/1rNE37FvYxkNSbIRvYXTQlOReJzXExUq_IDYv4Oem4NE/edit)

**Comment by jessicazartler** [comment]
Thank you, sounds good! 

(Wanted to file Jake's docs as there is a lot of good stuff in there to be integrated - wanted to have them all in one place for reference as we will build this into a piece at some point)

Huge thanks to @Jeff-Emmett for that work!

**Comment by jessicazartler** [comment]
Pulled from Hatch Outreach FAQ doc https://docs.google.com/document/d/16UI-EfD4qcwBaAv3Eexlv01SOK7oiDt4gkVT5rEY6X4/edit#

The following parameters will be voted on during the Hatching Process:

Support Required
Minimum Quorum
Vote Duration
Vote Buffer
Vote Execution Delay
TollGate Fee
Hatch Minimum Goal
Hatch Maximum Goal
Hatch Period
Hatch Exchange Rate
Hatch Tribute
Hatch Oracle Ratio
Maximum IH Raise
Expected Raise/IH
