### ISSUE TITLE
Create templates that Hatchers and Proposals can use to submit 

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#153]
Subtasks 

- which form app to use (same as on commonsstack now?)
- collaboration with comms for messaging
- review with dev to make sure details are 1005 valid
- review with legal
- launch them

**Comment by GriffGreen** [comment]
1. which form app to use (same as on commonsstack now?)

Would love to use the Commons Stack typeform, ping me on telegram/discord to do the form

**Comment by cranders1** [comment]
@GriffGreen I think I am willing to take on the typeform backend after better understanding of workload. Will ping TG.

**Comment by tamarandom** [comment]
@GriffGreen @cranders1 @eduardovegap This is all good in the Forums for proposals. Is there anything left to do in this issue or can we close it?

**Comment by eduardovegap** [comment]
I think we can close it.

**Comment by cranders1** [comment]
Agree with eduardo
