### ISSUE TITLE
TEC Lab weekly sessions 

### ISSUE THREAD

**Issue by liviade1** [TECommons/coordination#156]
## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by LinuxIsCool** [comment]
I created an organizational worksheet here: 

https://docs.google.com/spreadsheets/d/1C_q3LTmZipSNnptrAtLhr7inqy_8bm7aBU5bQ3uzPDI/edit?usp=sharing

**Comment by tamarandom** [comment]
Hey @LinuxIsCool - I'm going to close this issue. You've got it way under control outside of our Sprints. 🙏🏼
