### ISSUE TITLE
Decide on email/newsletter/CRM platform for TEC - Hubspot/Mailchimp/Substack

### ISSUE THREAD

**Issue by jessicazartler** [TECommons/coordination#165]
## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@krisjpi @jessicazartler

**Comment by markoprljic** [comment]
@cranders1 Did you get a chance to look into this? 
We will need to collect email addresses from the TEC website and would most probably need to set it up directly from Wordpress using (I assume) Mailchimp plugin. 

Please let me know the status of your decision and the next steps. 
Thanks.

**Comment by cranders1** [comment]
@markoprljic I am deferring to @knobsdao on this. 
He is leading up the CRM piece for TEC, simultaneously working on the CSTK revamp.
I will work with Dan on TEC migration and management when ready. Sounds like it is close.

**Comment by markoprljic** [comment]
> @markoprljic I am deferring to @knobsdao on this.
> He is leading up the CRM piece for TEC, simultaneously working on the CSTK revamp.
> I will work with Dan on TEC migration and management when ready. Sounds like it is close.

Thanks!

@knobsdao I guess the same question then to you :)
Do we have a decision on what we're using for email/newsletter as well as CRM?
We would like to move forward and close the decision as well as set up so that we can implement the integrations on our website and/or elsewhere.

**Comment by knobsdao** [comment]
Hey @markoprljic! Over CS we are migrating from MailChimp to Hubspot and will support doing that setup for TEC for both email campaigns/CRM. Status: Removed some blockers last week. Also, @GriffGreen is helping me with some spreadsheet magic for the data import. Aiming to have Hubspot for TEC set up this week.

Quick question: Is there an admin email to do the setup from? Then I'll pass it over to Craig.

Also, not 100% sure if TEC will take on Substack for newsletters. Maybe @jessicazartler knows?

**Comment by cranders1** [comment]
Good news @knobsdao. Ready to help with migration and take over backend mgmnt for tec.
Just ping me when ready to sync up.

**Comment by tamarandom** [comment]
YES! @cranders1 !!! 🙌🏼

**Comment by markoprljic** [comment]
Looks like we have made the decision to use:

- Hubspot 
- Substack


@knobsdao @cranders1 Can we close this issue?

**Comment by knobsdao** [comment]
@markoprljic Yes! @cranders1 I made a TEC Hubspot (sent the logins to @jessicazartler).

Thinking about your comment on capturing emails. There is a [HubSpot WordPress plugin](https://www.hubspot.com/products/wordpress) that may be useful. The other option is to capture them from SubStack directly, which would make sense if the CTA is a "Join Our Newsletter". If something different, then HubSpot. Is there a different issue closer in relation to subscriptions/emails/etc.? So we can close this one.

**Comment by cranders1** [comment]
Thnx for update @knobsdao. Its all still greek to me. Hubspot & Substack.

I need guidance on both platforms. Whenever you have space for a work session Dan.

@jessicazartler if you can send me the login credentials or the like, I can start peering inside :)

**Comment by markoprljic** [comment]
> HubSpot WordPress plugin

@knobsdao Yes, there's this issue related. I'm adding your note on Hubspot WP plugin. https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/tecommons/coordination/325

**Comment by markoprljic** [comment]
@cranders1 @knobsdao Next step after this has been decided is this issue. Moving on there :)
