### ISSUE TITLE
Praise Quant / News Blog: Nov. 21 - Dec. 4

### ISSUE THREAD

**Issue by jessicazartler** [TECommons/coordination#172]
## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@GriffGreen @liviade1

**Comment by jessicazartler** [comment]
https://medium.com/token-engineering-commons/now-accepting-proposals-for-funding-exploring-ostroms-principles-6238d0089a98

**Comment by jessicazartler** [comment]
@tamarandom did you mean to reopen this?

**Comment by tamarandom** [comment]
Nope. Booboo! It's covered here : https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/tecommons/coordination/347
