### ISSUE TITLE
Onboarding Working Group manifesto : Revisit and refresh!

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#180]
## 📋   Anything to add?

Revisit and revise. 

The Working Group manifesto will be a key part of the proposal for each working group. Does it still accurately reflect the goals and objectives of the working group moving forward? 

## 🎉   Subtasks

- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by iviangita** [comment]
Closing this as requested by @eduardovegap as he doesn't have the powers yet
