### ISSUE TITLE
Communications Working Group manifesto : Revisit and refresh

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#182]
## 📋 Anything to add?

Revisit and revise!

The Working Group manifesto will be a key part of the proposal for each working group. Does it still accurately reflect the goals and objectives of the working group moving forward?

## ❓ Why is it important?

The Working Group manifesto will be a key part of the proposal for each working group. 

## 🤼‍ Reviewer

@jessicazartler 

## 🔗 Work doc - inspirational links

https://docs.google.com/document/d/17w_UVi7lJjUNtj1Ji1WGd7Osk-E0edmfIRNoGRSP3yI/edit#heading=h.4qr126s3qfr1

WG description in the forum https://forum.tecommons.org/t/comms-working-group/162

**Comment by markoprljic** [comment]
@tamarandom @jessicazartler Can you please paste the link to the Communications WG Manifesto? Thanks.

**Comment by jessicazartler** [comment]
https://docs.google.com/document/d/17w_UVi7lJjUNtj1Ji1WGd7Osk-E0edmfIRNoGRSP3yI/edit#heading=h.4qr126s3qfr1

Here is also the WG description in the forum https://forum.tecommons.org/t/comms-working-group/162

Thank you!

**Comment by jessicazartler** [comment]
Durgadas has offered to take this on but he is not on Github so @markoprljic if you can coordinate with him to check on this - thanks!

**Comment by markoprljic** [comment]
Seems not :/ We need someone else.

**Comment by markoprljic** [comment]
@Zeptimus to help, thanks, buddy! :)

**Comment by markoprljic** [comment]
@Zeptimus Any progress on this? 

Thanks! :)

**Comment by Zeptimus** [comment]
Hey guys, i updated the manifesto would be nice @freedumbs00 @JessicaZartler @markop  one of you take it a look and accept or decline the sugestions. Regarding the members i think it would be a nice idea on next comms sync to encourage other members of comms to add their names motivations etc there.

https://docs.google.com/document/d/17w_UVi7lJjUNtj1Ji1WGd7Osk-E0edmfIRNoGRSP3yI/edit#heading=h.4qr126s3qfr1

**Comment by jessicazartler** [comment]
INTEGRATED/UPDATED -- Thank you so much @Zeptimus @GriffGreen for your feedback, one last question for Griff, otherwise I incorporated all feedback and added a few things.. will bring up in Comms meetings to make sure we have all current contributors listed and revisit time commitments.. otherwise going to go ahead and close - thank you everyone!
