### ISSUE TITLE
Conflict Management Working Group manifesto : Revise and refresh

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#183]
## 📋 Anything to add?

Revisit and revise!

The Working Group manifesto will be a key part of the proposal for each working group. Does it still accurately reflect the goals and objectives of the working group moving forward?

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by JuankBell** [comment]
Uptaded 28 jan, Roadmap until 11 march. (first generation of Gravitons on hatch week) :D

Gravity WG manifesto: https://docs.google.com/document/d/1yrEcPoOW8Q1qDE-YWWF0MhXlcvpiMk0jmdQx25nfZ6k/edit#
