### ISSUE TITLE
Start TEC roadmap during Hatch phase and beyond

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#188]
## 📋   Anything to add?

We have the roadmap to Hatch, what is our roadmap look like during the Hatch Phase and beyond? 

## 🎉   Subtasks

- [x] Working session with TEC Stewards 

## 🤼‍♂️   Reviewer

@

## 🔗   Work doc - inspirational links

Miro board : https://miro.com/app/board/o9J_lbkGJHQ=/

**Comment by tamarandom** [comment]
@markoprljic I have a call with @eduardovegap tomorrow at 10am to finish the Hatcher Outreach section. Shall we do Comms at the same time?

**Comment by markoprljic** [comment]
Friday? What do we have for comms, please remind me.

**Comment by tamarandom** [comment]
Here you go @markoprljic ! ;) 
https://miro.com/app/board/o9J_lbkGJHQ=/

I'll add this link to the body of this issue & dm you for a time slot on Friday.

**Comment by tamarandom** [comment]
Done. 
The Commons Swarm and TEC Params have the most detailed milestones due to the nature of these deliveries being the crux of the Hatch and Commons upgrade. Other working groups are nearing operational modes and continue will continue pieces of work as they arise.
https://miro.com/app/board/o9J_lbkGJHQ=/
