### ISSUE TITLE
CRM dedicated to TEC 

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#197]
## 📋 Anything to add?

Separate from CS. 

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by tamarandom** [comment]
Hey @cranders1 ! Is this a dupe of #166?

**Comment by cranders1** [comment]
I guess. The CRM Github stuff is confusing as hell to me. Seems like numerous people make related issues and assign them to me.

I have volunteered to head-up the CSTK to TEC CRM transition. Could be 1 of 4 or 5 issues?
Working with Dan directly.
But until Dan does all the stuff necessary, I have no action items other than pestering him, which I have been doing too much already.

Once we transition, I will actively manage CRM issues. Until then, seems the creators of those issues need to chime in on the intent.

**Comment by tamarandom** [comment]
Hey @cranders1 !  Right now, the only issues related to CRM are this one and and #166.

**Comment by markoprljic** [comment]
Do we need this issue since we already have a similar?

**Comment by tamarandom** [comment]
Update : @knobsdao will send email to CS TS to opt-into email comms from TEC. Then the CRM can go live.

**Comment by knobsdao** [comment]
Updates: @markoprljic @cranders1 @tamarandom I ran into a blocker recently in CS' HubSpot. Setting up dedicated CTA buttons is a paid feature and I initially planned to have a one click opt-in. Could a button directing to the TEC website be the best option? We could set up an email signup linked to HS there or something similar.

I'm trying to find the best way. Open to discuss it in more detail. There's some valuable data points recollected in the Trusted Seed Typeform that link to TEC which I want to help transition safely. Managing data "respectfully" is complex.

Anyhow, migration on our side, including better categorization and data integrity on TS is almost done. That'll unblock way more useful/targeted email campaigns.

**Comment by markoprljic** [comment]
> Could a button directing to the TEC website be the best option? We could set up an email signup linked to HS there or something similar.

@knobsdao Yes that could work as well.

**Comment by tamarandom** [comment]
Hey @markoprljic - Are we ok to close this?

**Comment by markoprljic** [comment]
The pleasure is all yours :)

**Comment by tamarandom** [comment]
🤗
