### ISSUE TITLE
TEC Soft Gov: Automated Options for Onboarding & Rewards Systems Documentation 

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#203]
## 📋   Anything to add?

12/23 Housekeeping: Moved this issue from the [CS repo](https://app.zenhub.com/workspaces/core-team-organization-5f1206c0362e7b000fc0161b/issues/commons-stack/iteration0/219) to TEC repo.
@jessicazartler, @liviade1 : assigning to @eduardovegap. It fits into the Onboarding WG, right? 

--

CC from TEC https://github.com/TECommons/Coordination/issues/14

## 🤼‍♂️   Reviewer

@liviade1 @GriffGreen 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/16fZG4QJycKDTGrJAKWT-caflBE3g53o1L2k64ztIlZM/edit?userstoinvite=liviaieaou%40gmail.com&ts=5f9a0367&actionButton=1

**Comment by jessicazartler** [comment]
Heya @tamarandom this should actually be split... there is automated onboarding (which is really the new Discord and I think is mentioned there already) and the second epic is under Soft Gov - and that is reviewing the rewards systems which has two parts:
1) Automated = source cred, project by Santi/Mateo
2) Human quant = TBD @liviade1 how and if we want to continue the praise system

**Comment by tamarandom** [comment]
I see what you mean @jessicazartler. The original post is from late Oct. and I have a hunch this issue should be closed as it is already addressed in several others : 

#167 setup new discord <-- needs refinement 
#6 subscribe bot for Discord 

#192 sync on SourceCred params for TEC
#193 integration of praise and SourceCred

I do not think there is yet an issue on "how and if we continue" praise but if that's not already under the scope of #193 and it needs to be tackled, then we can open an issue for it.  @liviade1, do we open an issue to examine and track that?

**Comment by tamarandom** [comment]
Closing this!
