### ISSUE TITLE
Identify WG proposals and assist their submission using the new process

### ISSUE THREAD

**Issue by iviangita** [TECommons/coordination#215]
## 📋 Anything to add?

Copied from CS repo [issue 357](https://app.zenhub.com/workspaces/commons-stack-workspace-5f1206c0362e7b000fc0161b/issues/commons-stack/iteration0/357)

## 🎉 Subtasks

- [x]  Make a list of proposals that are emerging
- [ ]  speak to the proponents to make sure the new process is used

## 🤼‍ Reviewer

@

**Comment by liviade1** [comment]
- audit proposal from transparency
- Source Cred proposal 
- flagging proposal from Gravity
