### ISSUE TITLE
support Ata on the TEC case study

### ISSUE THREAD

**Issue by iviangita** [TECommons/coordination#218]
## 📋 Anything to add?
Continual support on this. Repeating every week.

Copied from CS repo [issue 356](https://app.zenhub.com/workspaces/commons-stack-workspace-5f1206c0362e7b000fc0161b/issues/commons-stack/iteration0/356)

## 🎉 Subtasks

- [x] weekly interviews
- [x] wednesday sessions
- [x] review part of the interviews doc

## 🤼‍ Reviewer

@

**Comment by tamarandom** [comment]
Hi @liviade1 Closing this issue after the convo in yesterday's Sprint planning call about this work being in under the scope of Commons Stack not TEC actually. ;) So let's stick with the issue that exists in that repo.
