### ISSUE TITLE
Soft Gov / T&C Telegram

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#230]

**Comment by freedumbs00** [comment]
Livia is this complete?  Was my contribution for Telegram satisfactory? Do I need revise or will suffice and can I close this?

**Comment by freedumbs00** [comment]
https://docs.google.com/document/d/1JxP8Pgm62ANZCbAQqZiVOYxc-OTQc0o4AGzNBgI5Q_M/edit?usp=sharing

**Comment by freedumbs00** [comment]
Completed task for Telegram and waiting for review of whole document.  Reassigned @liviade1 .  You're awesome!!

**Comment by tamarandom** [comment]
This T&C is included in the Code of Conduct. Closing!
