### ISSUE TITLE
Soft Gov / T&C Github

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#233]

**Comment by Santigs** [comment]
Created first iteration of the terms document
I used https://stackedit.io/app# to hack Aragon terms

**Comment by Santigs** [comment]
[TEC Contributor License Agreement (CLA).pdf](https://github.com/TECommons/coordination/files/5821657/TEC.Contributor.License.Agreement.CLA.pdf)

**Comment by freedumbs00** [comment]
@liviade1 are you going to continue with you're work sessions to finish this?

**Comment by freedumbs00** [comment]
Everything has been done.  Closing issue
