### ISSUE TITLE
Soft Gov / T&C TEC Hatch

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#234]

**Comment by liviade1** [comment]
We just need to incorporate comments

**Comment by tamarandom** [comment]
Update: next step to merge into gitbook then close ;)

**Comment by Santigs** [comment]
Here's the link to the Hatch Terms created in Legal WG
https://docs.google.com/document/d/1voxAC_XZfbElTF8NRDTrB4Kaz3Js2J9ShvHx5FsUcdA/edit?usp=sharing

**Comment by tamarandom** [comment]
@liviade1 @Santigs  Is this one ready to close or do we pull it into the next Sprint?
