### ISSUE TITLE
Legal / T&C TEC Hatch

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#244]

**Comment by Santigs** [comment]
This is the original ANJ document we are using as a baseline https://anj.aragon.org/legal/terms-general.pdf
And this is the [working document](https://docs.google.com/document/d/1voxAC_XZfbElTF8NRDTrB4Kaz3Js2J9ShvHx5FsUcdA/edit)

**Comment by Santigs** [comment]
document is finished in its draft version. We need some members of the legal working group to go over. it.

**Comment by tamarandom** [comment]
Update : closed
