### ISSUE TITLE
Decide if we do DAO Rush Week Participation

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#259]
## 📋 Anything to add?

From Niran:
Here's the video from the DAO Rush Week planning call (apologies for the choppy audio): https://drive.google.com/file/d/13r2170O0Hw2KnxKlHik-3oKxkdm433cf/view?usp=sharing

Here are the slides with all the instructions and the email address you'll need to add events to the DAO Rush Week calendar: https://docs.google.com/presentation/d/1g5TrAZP9dqGUg-AlV1eRkgfKBYKIQDS0PZrcLHsvyEA/edit?usp=sharing

## ⏰ Urgency/Due Date/Blockers?

YES! We would need a Slide before Jan 7th!

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by freedumbs00** [comment]
https://docs.google.com/presentation/d/1NIEre5ifvvRVqjT7j5iyKTGZsW3QN8LX9R7ZqAKW1Us/edit#slide=id.g87e184e963_0_136. 

Slide 21 is ours.   We will be presenting on Weds. the 13th at 9AM EST.   tentatively...   lol
