### ISSUE TITLE
Train community members in the art of recording calls

### ISSUE THREAD

**Issue by iviangita** [TECommons/coordination#260]
## 📋 Anything to add?

This will be a monthly session to train members who are interested to contribute to the Transparency WG by recording calls.

Training session schedule:
-Jan 6, 2021

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by iviangita** [comment]
Closing! Here's the [training session.](https://www.youtube.com/watch?v=qiRu-NRgso0)

**Comment by tamarandom** [comment]
@Zeptimus @iviangita Would it make sense to include this training session video link on the Transparency WG agenda & notes and the WG cal invite? That way it will be easy for all interested in Transparency WG to find.

**Comment by Zeptimus** [comment]
Thats a great idea Tam!
