### ISSUE TITLE
Establish a system of recording calls (e.g. schedule, person in charge, etc.)

### ISSUE THREAD

**Issue by iviangita** [TECommons/coordination#261]
## 📋 Anything to add?
Have a documented process of recording calls

## 🎉 Subtasks

- [ ] Invite volunteers regularly (when)? 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

## 🔗 Work doc - inspirational links
Refer to Goal 3 in the [Transparency Manifesto](https://docs.google.com/document/d/19-YlxdBuivR6qwSTPvlSP6kSLExUDSYT5frp7qaArFI/edit#)

**Comment by Zeptimus** [comment]
Closing, We will present the system next thursdays january 14.
