### ISSUE TITLE
Revisit and improve the system of uploading videos on Youtube/Lbry

### ISSUE THREAD

**Issue by iviangita** [TECommons/coordination#262]
## 📋 Anything to add?
This will be for Transparency WG members who have access to the TEC Youtube channel

## 🎉 Subtasks

- [ ] Update playlist and database
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by iviangita** [comment]
Hey @Zeptimus I think we had also covered this in [issue 261](https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/tecommons/coordination/261)? If so, can we close this? :)

**Comment by Zeptimus** [comment]
Close
