### ISSUE TITLE
Coordinate the Transparency WG system to the community members

### ISSUE THREAD

**Issue by iviangita** [TECommons/coordination#263]
## 📋 Anything to add?
Volunteers can fill up their names in there: https://docs.google.com/spreadsheets/d/112KJwcH0cF87wlKJa5g9Ob5Rtj2Axp0jNs14yP8tbVs/edit#gid=0

## 🎉 Subtasks

- [ ] Keep the community engage during thursday calls.
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by Zeptimus** [comment]
Close
