### ISSUE TITLE
30 min weekly onboarding sessions

### ISSUE THREAD

**Issue by liviade1** [TECommons/coordination#265]
## 📋 Anything to add?

The barrier to enter is getting higher now that working groups are in an advanced state, let's have some open calls for anyone to come and ask any questions :) 

## 🎉 Subtasks

- [ ] edit calendar of both onboarding wg and this onboarding sessions so the intention of each call it's clear for everyone 
- [ ] comms invite 
- [ ] promote on twitter and TE channels 

## 🤼‍ Reviewer

@jessicazartler

**Comment by jessicazartler** [comment]
ETA for starting so I can make you da graphic? Thank you!
