### ISSUE TITLE
add a disclaimer to the proposals template 

### ISSUE THREAD

**Issue by liviade1** [TECommons/coordination#269]
## 🎉 Subtasks

- [ ] explain that we are in a PRE proposal phase where the full amount for the projects being submitted are important now because they will give a better idea for how much we need to hatch, but later, when they are submitted to the Commons is better we have smaller milestones, so a project might be broken down into multiple proposals :) It won't be much extra work, but it's nice that people don't have surprises later and have time to develop the budget with details. 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by jessicazartler** [comment]
@liviade1 should we close this issue? I finished my part which was the original reason for this issue --  I know you are taking it forward but not sure if we should make a new issue for your work and close this one?
