### ISSUE TITLE
Onboarding Hatchers 

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#277]
## 📋 Anything to add?

Tracked in tec_curate during weekly Onboarding calls. 

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by eduardovegap** [comment]
can we close this one? it's very similar to #207 @tamarandom

**Comment by tamarandom** [comment]
Hey @eduardovegap ! #207 is an epic. You won't see that if you are on github.com directly as epics are part of the zenhub view. If you look on zenhub, it becomes clear : https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/tecommons/coordination/207

This issue, #277, is a repeating task. Label is "#repeating : sprint" and it's the one that get pulled into every new sprint as this is a piece of work you are driving every week. 

That said, I do think we can consolidate these Hatch Outreach issues for more clarity.

**Comment by tamarandom** [comment]
Hey @eduardovegap After our session today and the Hatch Outreach Epic, this one we close for good, yeah?
