### ISSUE TITLE
Why are TE Public Goods Important? Post/Article

### ISSUE THREAD

**Issue by jessicazartler** [TECommons/coordination#294]
## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@GriffGreen @tamarandom 

## 🔗 Work doc - inspirational links
Building on https://forum.tecommons.org/t/tec-funding-proposals-what-kinds-of-projects-should-apply/191

**Comment by markoprljic** [comment]
@jessicazartler This issue is about refactoring the forum post, maybe add intro text and repost on Medium? Not actually writing the whole post, right?

Can you deliver in this sprint?

**Comment by jessicazartler** [comment]
Yups :D

**Comment by markoprljic** [comment]
@tamarandom Following up from our call today, is it safe to close this issue? Are we dropping this piece?

**Comment by jessicazartler** [comment]
It is in progress, I am just checking in with Griff as he had asked for this piece and wanted to get his inputs - will circle back after I hear from him

**Comment by jessicazartler** [comment]
Finished writing - one last glance by KrisJ/if Griff has time then I will be publishing :D 

https://docs.google.com/document/d/1eMjuxzf_AWwNuj-4yucUC5vYvF72Ol_pad2lNkWLgzs/edit

**Comment by jessicazartler** [comment]
https://medium.com/token-engineering-commons/wielding-promethean-fire-the-importance-of-te-public-goods-9afba0ce5a43

Moving to distribution

**Comment by tamarandom** [comment]
It's beautiful!
