### ISSUE TITLE
TEC Stories Series : The Why

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#298]
## 📋 Anything to add?

A "why" piece on the TEC / update to the Kickoff article https://medium.com/token-engineering-commons/kicking-off-the-token-engineering-commons-be6a253cba81

## 🎉 Subtasks

- [x] Jess write draft
- [x] Pass it around for edits
- [x] Publish & distribute

## 🤼‍ Reviewer

@cranders1 

## 🔗 Work doc - inspirational links
https://docs.google.com/document/d/1B5vTASE5nzVzW14OqrBeWDGXZzBqgobnmu4HBKKAgis/edit

**Comment by jessicazartler** [comment]
https://medium.com/token-engineering-commons/towards-robust-and-resilient-economies-and-communities-8effcc5bc20d
