### ISSUE TITLE
 New Discord / Deciding channels/categories

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#301]
## 📋 Anything to add?

We need to have preliminary Discord categories to build out Discord channels and continue with onbaroding.

## ⏰ Urgency/Due Date/Blockers?

**Due on Wednesday, Feb 3, 2021**
No blockers.

## ❓ Why is it important?

Very important so that we can migrate Discord soonest possible

## 🎉 Subtasks

- [x] Jess review draft categories 
- [ ] Edit/Approve and close issue

## 🤼‍ Reviewer

@jessicazartler 

## 🔗 Work doc - inspirational links
https://docs.google.com/document/d/1Cr_GSoGaW7SfslvIMwtFvoyj1U7i1EWWvtO2Euj7_e4/edit#heading=h.bq2alzcp5km

**Comment by jessicazartler** [comment]
Need to discuss with Angela the migration

**Comment by markoprljic** [comment]
Jess discussed with Angela, confirmed we can continue with the migration.
Related issue #304

**Comment by markoprljic** [comment]
@jessicazartler needs to review, blocking @metaverde to move forward.

**Comment by jessicazartler** [comment]
Got admin powers for Discord -- started building the basic channels, have a work session with MetaVerde Wednesday to polish/discussion and decide next steps to push forward the Discord

**Comment by freedumbs00** [comment]
Can Eduardo get involved in this as well?

**Comment by jessicazartler** [comment]
Yeah sure I'll DM him thanks

**Comment by jessicazartler** [comment]
Set up basic categories and had a work session with MetaVerde to handoff the lead on taking this forward but this one is done! :D
