### ISSUE TITLE
New Discord / Planning launch campaign 

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#302]
## 📋 Anything to add?

 Planning launch campaign w/ newsletter/medium/forum? + distribution / migrating everyone - sync Angela/Sebnem (Jess/Kris Comms WG)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by jessicazartler** [comment]
Needs owner -- maybe @markoprljic ?

**Comment by jessicazartler** [comment]
Dup #319 needs owner
