### ISSUE TITLE
New Discord / Designing onboarding journey

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#303]
## 📋 Anything to add?

Designing onboarding journey (Eduardo/Craig/Kris/Jess) -- Kris let us know when he needs feedback

## ⏰ Urgency/Due Date/Blockers?

Soonest possible.

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@markoprljic @liviade1 @eduardovegap @cranders1 

## 🔗 Work doc - inspirational links
Onboarding journey miro board https://miro.com/app/board/o9J_kkC0kIM=/

**Comment by jessicazartler** [comment]
@Metaverde is willing to support 
Coordinate with KrisJ on CS side to see what he's got so far and improve

**Comment by tamarandom** [comment]
Hey @krisjpi ! @Metaverde is going to be great on this! She's been working with 1Hive and they nailed onboardong journey on their Discord. Simple and clean. Can you please share with her what we have on this & bring her into the TEC Discord.

**Comment by tamarandom** [comment]
Working session with @eduardovegap @metaverde and myself. Here is a first pass of what it **_can_** look like. 

Would love feedback for any part of this journey from @jessicazartler @liviade1  @GriffGreen @krisjpi @markoprljic  🙏🏽 🥚 🐣 🐥  🙌🏽

https://docs.google.com/document/d/1Ma4bkLyk1ys_qT22PvD99QQkztketuwF-UxeOoxZ2-k/edit

**Comment by markoprljic** [comment]
Great start! Left comment in the doc.

**Comment by tamarandom** [comment]
@markoprljic @metaverde @eduardovegap Please have a look at the new discord onboarding doc. It has been updated to incorporate feedback from @krisjpi . 

https://docs.google.com/document/d/1Ma4bkLyk1ys_qT22PvD99QQkztketuwF-UxeOoxZ2-k/edit

**Comment by eduardovegap** [comment]
I love the NBA example, I think that should be the way the T&C should be presented. I am glad is taking shape.

**Comment by markoprljic** [comment]
Love the NBA as well. 
Great onboarding so far. Moving on!

**Comment by jessicazartler** [comment]
If you all want to present in the Comms meeting tomorrow and walk us through as if we were new user we can give some feedback.. would be cool

**Comment by eduardovegap** [comment]
shall we close this? @tamarandom or is it more sessions of onboarding journey that needs to be done?

**Comment by tamarandom** [comment]
Left to do : 
(Kai ) bridges to TG 
Determine to whom to pass

Invite TEC stewards now ! https://discord.gg/tQUjt4BB4C

**Comment by tamarandom** [comment]
Opened new issues for the last two pieces to put into place so we can close this one! 

#440
$444
