### ISSUE TITLE
New Discord / Implementing spam blocking measures

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#305]
## 📋 Anything to add?

 Implementing spam blocking measures (Kris/Durgadas) -- Async

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by markoprljic** [comment]
@krisjpi Related to[ this issue](https://app.zenhub.com/workspaces/samurai-shark-5fff2ff3773cf800118fd99c/issues/tecommons/coordination/307), I have a similar question. Can you give an estimate on this?
Thanks!

**Comment by krisjpi** [comment]
So for this one @tamarandom, I think it may still be relevant. I will observe and investigate the best way to handle spam that we are seeing in the server. Some of the spam should be handled by the verification bot/claiming a role, but there may be more efforts required if we notice that server members are receiving a lot of unsolicited spam via DM.

Let me know if this becomes an issue, and I will prioritize.

**Comment by markoprljic** [comment]
Thanks @krisjpi Let's keep this one open until we see the need.

**Comment by tamarandom** [comment]
Hey @krisjpi @markoprljic I agree. Let's assume that the bot check works as expected. ;) This can sit in the product backlog for another sprint or two and the we can close it once we know it's doing it's job.

**Comment by tamarandom** [comment]
Hey @krisjpi @markoprljic - Going to close this out now. 

There is a separate issue, #499, to review the discord onboarding journey to achieve a higher success rate. That one will take into account the need for spam-bot preventative measures.
