### ISSUE TITLE
New Discord /  Boosting/making sure we have capacity for call channels

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#306]
## 📋 Anything to add?

 Boosting/making sure we have capacity for call channels (Kris/Tanner)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by jessicazartler** [comment]
We figured out there are some hard rules for 25ppl in a call, without video, there is space for more -- forgot this has been discussed and solved for now.
