### ISSUE TITLE
New Discord / Bots 

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#307]
## 📋 Anything to add?

From previous issue that was turned into an epic. 

Define and implement the bots needed on our new Discord. 

---
 BOTS NEEDED: bot for sign up (maybe include email and merge w/ subscribe bot for newsletter Github issue #6 
                                   Do we want to have a faucet?

---
## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by markoprljic** [comment]
@krisjpi When do you think you can dedicate some time to work with @metaverde on this issue? To speed things up we could also ask other people to contribute. Please let us know if this works for you so.

**Comment by markoprljic** [comment]
Since this issue only mentioned sign up bot, does this mean we can close this issue? 
@metaverde  @krisjpi Can you give an update on this, please?

Thank you.

**Comment by krisjpi** [comment]
I think this can be closed @tamarandom as like you said, this only references the sign up/verification bot, which is currently working. I am happy to add additional bot functionality to the server as needed though!

**Comment by tamarandom** [comment]
Hey @krisjpi @markoprljic Good by me to close this. If more bots are needed, we can open new issues to address them as need arises.
