### ISSUE TITLE
Dev. contribution with Token Log specific in React and Typescript

### ISSUE THREAD

**Issue by freedumbs00** [TECommons/coordination#311]
## 📋 Anything to add?

Help with multiple tokens on Token Log to create balance over supply with the two tokens cstack and impact hours.  

@wslyvh 

## ❓ Why is it important?

moving forward with creating a standard simplified voting procedure

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@GriffGreen

**Comment by wslyvh** [comment]
There's an open PR to track the work. If anyone's interested to contribute
https://github.com/wslyvh/tokenlog/pull/16

**Comment by freedumbs00** [comment]
@wslyvh completed on his own.  Closing issue.  https://deploy-preview-16--tokenlog.netlify.app/TECommons/coordination
Looks fantastic.
