### ISSUE TITLE
Article : New to the TEC

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#316]
## 📋 Anything to add?

Run with this in whatever direction feels authentic to you. 
Shout out to @jessicazartler if you need.

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@jessicazartler @tamarandom 

## 🔗 Work doc - inspirational links
https://docs.google.com/document/d/1MqiJsWZqV18wrzZhJC6kcgaOX0jiej2Tj6ZinJFNSVg/edit?usp=sharing

**Comment by tamarandom** [comment]
Hey @natenatesoo, can you pass me your article. I don't know what editing it needs but in answer to @jessicazartler's call for a volunteer on the comms call just now, I raise my hand. (I'm a pretty decent editor.)

**Comment by jessicazartler** [comment]
Updated in description
https://docs.google.com/document/d/1MqiJsWZqV18wrzZhJC6kcgaOX0jiej2Tj6ZinJFNSVg/edit?usp=sharing

Thanks Tamara!!!

**Comment by tamarandom** [comment]
@natenatesoo I linked a first pass edit in a link at the bottom of that doc. Let me know what you think & I can do a second pass Thursday or later this week.

**Comment by tamarandom** [comment]
@natenatesoo : second pass draft ready for you to look at. [https://docs.google.com/document/d/1XgWzi3OvhC1eSv-urVOkOjNqAEtILM3PtUobqYX4Rus/edit](https://docs.google.com/document/d/1XgWzi3OvhC1eSv-urVOkOjNqAEtILM3PtUobqYX4Rus/edit)

**Comment by markoprljic** [comment]
@jessicazartler Putting you on the issue just as a reminder to publish on Medium when you sync with Nate on this.

**Comment by jessicazartler** [comment]
This looks great to me don't think it needs further edits @tamarandom you said go yes if Nate is good?
Messaging Nate now about Medium and once up, will move to distribution
