### ISSUE TITLE
New Discord / TE --> TEC Migration

### ISSUE THREAD

**Issue by jessicazartler** [TECommons/coordination#319]
## 📋 Anything to add?

Handling everything with the migritation -- promotion, archiving, etc

Notes from Metaverde:

Migrating channels
https://github.com/BilliAlpha/discord-transfer
GitHub
BilliAlpha/discord-transfer
A discord bot for copying messages between guilds. Contribute to BilliAlpha/discord-transfer development by creating an account on GitHub.

Another option is to clone the server then change it up.
https://support.discord.com/hc/en-us/community/posts/360055401412-Server-Duplicating-Cloning-
https://top.gg/bot/xenon

## ⏰ Urgency/Due Date/Blockers?

Soonest possible.

## ❓ Why is it important?

Other connected issues.

## 🤼‍ Reviewer

@markoprljic

**Comment by krisjpi** [comment]
Met with Metaverde and sorted out a plan and talked through where we are on the TEC Discord onboarding process. 

The server exists, but is not officially launched yet. It can be launched at any time, especially if we want to build out onboarding flows after the launch. @markoprljic - Metaverde relayed some of your questions, feel free to shoot me a message if you have any outstanding ones!

**Comment by markoprljic** [comment]
> The server exists, but is not officially launched yet. It can be launched at any time, especially if we want to build out onboarding flows after the launch. 

This is great to hear Kris! :)

I would do the following:

1. Launch it now!
2.Build out channels based on the preliminary structure [outlined in this doc.](https://docs.google.com/document/d/1Cr_GSoGaW7SfslvIMwtFvoyj1U7i1EWWvtO2Euj7_e4/edit#heading=h.bq2alzcp5km) Related Issue https://app.zenhub.com/workspaces/samurai-shark-5fff2ff3773cf800118fd99c/issues/tecommons/coordination/304

Open issues:

1. How to transferer messages from TE server to TEC server? Process, effort and timeline estimate needed.
2. Onboarding UX (by Metaverde) From what I hear a lot can be copied from 1Hive's onboarding. 

I advocate for an agile approach and decide/fix things on the go as long as they don't have any deeper implications on future state of the server.

**Comment by jessicazartler** [comment]
I will be reviewing channels this week hope to finish by Friday latest

Please include @liviade1 @eduardovegap & @cranders1 if he wants? as reviewers for onboarding journey/flow discussions and work sessions - thanks!

**Comment by markoprljic** [comment]
> I will be reviewing channels this week hope to finish by Friday latest
We can add preliminary channels to Discord and adjust later.

> Please include @liviade1 @eduardovegap & @cranders1 if he wants? as reviewers for onboarding journey/flow discussions and work sessions - thanks!

This is the onboarding issue https://github.com/TECommons/coordination/issues/303 Mentioning them there.

**Comment by tamarandom** [comment]
@markoprljic I see you are on top of this. On the Stewards call today @metaverde volunteered to own the migration in addition to the user journey (#303). I assigned her just now but want to check in with you in case you had another idea for how to move it forward.

**Comment by markoprljic** [comment]
That is great news @tamarandom thank you.
Woohoo @metaverde 🙌

**Comment by metaverde** [comment]
I'm still not clear on whether we are migrating TEC channels from TE Discord or connecting the two servers with bots for those channels or if there was a third option?

I think if people will still be on both Discords connecting the two servers with bots for those channels is the best option.

**Comment by markoprljic** [comment]
Not sure, my gut says we migrate convos first but keep the bridge.

**Comment by jessicazartler** [comment]
We are fully migrating to new TEC and deleting all TEC channel out of TE EXCEPT one bridge channel
And will have one bridge channel on TEC side for TE -- does that make sense?
Thank you for asking and all of your hard work!

**Comment by metaverde** [comment]
Hmmm.
Ok.
Vyvy-vi and I have given up on getting permissions to actually do anything on the server and have cloned it.
We'll turn over ownership when we get the onboarding journey done.
I don't actually have weeks and weeks to work on something that shouldn't take a weekend to complete.
We'll probably need permissions to grab the channels off the TE Discord when we get there, or someone at TEC can do that after we turn it back over.

In the meantime, I need a description of Omega working group... couldn't find on the Forum,
as well as info on Stewards and on Labs.

Thank-you.

**Comment by markoprljic** [comment]
@JuankBell Making you the owner of this now.

**Comment by tamarandom** [comment]
Hey @JuankBell !

@vyvy-vi would like to know whom to set as the moderators and role permissions for TEC Team on our new Discord : 

Moreover, on which classification should the following roles be assigned:
- Moderators(I suppose ppl will volunteer) ( *moderators might have ban, mute, kick permissions on the server and maybe on the bots )
- TEC Team(I am not sure regarding the role and what power levels should this role be assigned- Should this include message pin perms and message deletion perms along with moderation permissions?)

**Comment by markoprljic** [comment]
Hi @JuankBell any update on this?

**Comment by markoprljic** [comment]
I recall the decision from Jess saying:

> We are fully migrating to new TEC and deleting all TEC channel out of TE EXCEPT one bridge channel
> And will have one bridge channel on TEC side for TE -- does that make sense?

I also noticed Kay setting up bridges for our new discord. Should we proceed as decided earlier?

**Comment by JuankBell** [comment]
Thanks everyone for their work in this issue!

Share with you some of the notes from today's stewards call.

Don't delete old channels, they are good archives. a lot of valuable information is there. 
we have to fix the bridges and look into this phase aiming to help all members engage and adapt to the new server.

**New Discord Server ideas / suggestions / plan  :**
Thursday Community call (tomorrow) announce 
Monday we start hosting calls on the new Discord (1week time adaptation period)
Change all links in Comms channels/platforms 

**New Link ---> https://discord.gg/tjhx4rw2WK**

When are we going to host our inauguration?
→ Next week’s Comm call 

To be done (not blockers)
Which bridges / channels on TE are valuable to keep 

Blockers : 
Praise bot
Bridged channels

**Comment by jessicazartler** [comment]
> I recall the decision from Jess saying:
> 
> > We are fully migrating to new TEC and deleting all TEC channel out of TE EXCEPT one bridge channel
> > And will have one bridge channel on TEC side for TE -- does that make sense?
> 
> I also noticed Kay setting up bridges for our new discord. Should we proceed as decided earlier?

This was some weeks ago - decentralized coordination --- please refer to Juan's post as the plan as it was discussed in stewards today - thank you!

**Comment by geleeroyale** [comment]
Alright - all channels should be bridged now. some rooms did not offer an obvious bridge target on the other side - these are unbridged for now:

```
no bridge obvious (TEC side):
  #🤖parameters 
  #🌾stewards
  and all categories except "working groups" & "general" in the category open

no bridge obvious (TE side)
  #🌱-tec-voting
```

**Comment by tamarandom** [comment]
Hey @geleeroyale 

@JuankBell @markoprljic @jessicazartler What are your thoughts on this? If we are keeping all the WG bridged then I propose we add #stewards and #params to the TE Discord and bridge it as well. To whom do I make that request though? And is that the direction we go? 

And for #tec-voting @liviade1 do we want that channel on the new TEC Discord? Under the "Open" channels?

**Comment by jessicazartler** [comment]
Thank you @geleeroyale you rock!! FYI for you and @tamarandom those channels were never created on TE side so there is nothing to bridge as they are "new" channels..

For voting, would you like to create a voting channel on TEC side where we could track voting or point to forum voting? and have it there for discussions? I think that could be good..

**Comment by tamarandom** [comment]
Hey @jessicazartler I tend to agree. A channel dedicated to votes will make it easy for everyone to see when there is an action they need to take wrt voting versus the votes getting buried in another channel. 

For the two wg without channels on TE Discord, I asked Angela if she would mind if we add them to TE discord so that we can bridge them to TEC discord. It would be inconsistent to have the others without these too. She gave the green light. 

Thanks for your patience while we work this out, @geleeroyale. Would you kindly : 

Create these on TE under "te-commons" and bridge them to the TEC channels please? 
  #🤖parameters 
  #🌾stewards

And create this on TEC and bridge to TE side
  #🌱-tec-voting

**Comment by Vyvy-vi** [comment]
I noticed that there is a #🔑 -tec-tokenholders channel
What is the purpose of this channel?

**Comment by Vyvy-vi** [comment]
@tamarandom @geleeroyale A `#🌱-tec-voting` channel has been added in the **OPEN** channels category on the TEC server.
Is this the correct category for the channel? (This can now be bridged to the TE discord)

**Comment by markoprljic** [comment]
@JuankBell  Praise bot and Bridged channels are done as far as I can see. 
When is the official TEC Discord migration party happening?

**Comment by markoprljic** [comment]
Confirmed, channels bridged and praise bot there.

**Comment by geleeroyale** [comment]
Yes - did those bridges. Sorry, forgot to mention it here. If anything needs to change just ping me :)
