### ISSUE TITLE
Refine Website Content for Homepage

### ISSUE THREAD

**Issue by jessicazartler** [TECommons/coordination#320]
## 📋 Anything to add?

Need to edit/finalize content for new homepage that is coming

## ⏰ Urgency/Due Date/Blockers?

Urgent.

## ❓ Why is it important?

Marko needs final content to finish the website design.

## 🤼‍ Reviewer

@markoprljic @freedumbs00 

## 🔗 Work doc

https://docs.google.com/document/d/1VOM39PVE41_GYKUbdZCZIu_xySDp60tLTXqup2-t27I/edit#

OLD
https://docs.google.com/document/d/1VOM39PVE41_GYKUbdZCZIu_xySDp60tLTXqup2-t27I/edit

**Comment by freedumbs00** [comment]
@jessicazartler  @markoprljic We had a call to move this forward.  Progress made and should be complete by next sprint to move forward with finalization.

**Comment by jessicazartler** [comment]
Content finished - we will have one meeting next week to finalize design - will create a separate issue for that - ya team Marko/JJ!
