### ISSUE TITLE
Modify the Wordpress theme based on the Website design

### ISSUE THREAD

**Issue by markoprljic** [TECommons/coordination#323]

**Comment by rosamoc** [comment]
Hi Marko, where can I find the last version of the design? Thank you.

**Comment by markoprljic** [comment]
Hi Rosa, it's not read yet, I'll ping you when it's done. Just created the
issue and assigned you for awareness. 🙂

**Comment by markoprljic** [comment]
Hi @rosamoc the new website design is ready to be ported to WP. Are you available to do this?
Is there anything you need from someone to get started, or are you blocked by anything? 

Please let me know. Thanks!

**Comment by markoprljic** [comment]
Oh sure! Here's the issue with preview and Figma link #322
Let me know if you have any questions.

**Comment by rosamoc** [comment]
Thank you Marko,

I like it!!
Just one question, about the titles, are they an image or there is a special font for them?

**Comment by rosamoc** [comment]
I'm thinking about the responsive website

**Comment by markoprljic** [comment]
Yes, these are all web fonts. We use Bai Jamjuree font and you can find all assets in this repo https://github.com/TECommons/tec-branding-assets

**Comment by rosamoc** [comment]
Ok , perfect!

And one more question, is the design psd?

**Comment by markoprljic** [comment]
No, it is in the Figma file that I shared link in the original issue.
Here https://www.figma.com/file/SKZCNjAWvoPqZA7xeS8HGb/TEC-Website?node-id=396%3A410

**Comment by rosamoc** [comment]
OK Thank you!!

**Comment by markoprljic** [comment]
@rosamoc We're planning our next sprint today. Can you please confirm if you will be able to work and complete this in the coming 2 weeks? Thank you.

**Comment by rosamoc** [comment]
@markoprljic Yes Marco, for now there is no problem to have it finished in two weeks. If I have any problem next week I will tell you something. In any case, your will be informed.

**Comment by markoprljic** [comment]
Thank you so much!

**Comment by markoprljic** [comment]
Hi @rosamoc 
Let me know when you start with this. Would be great to get a progress update during this week. 
Thanks!

**Comment by rosamoc** [comment]
Hi @markoprljic I have already started. I think I'm going to need Elementor Pro: Because of menus and buttons functionality. When I finish the first phase I will confirm it. 
Yes I will keep you updated.

**Comment by markoprljic** [comment]
Great news Rosa! 🤗
Thank you.

**Comment by rosamoc** [comment]
@markoprljic  Hi Marko, just two questions:
1. Where do the buttons and links go?
2. For the responsive versions, do you have a design already made or do I adapt it as best as I can?
Thank you!

**Comment by markoprljic** [comment]
@rosamoc 

1. Link all to forum
2. Adapt and we'll see later if improvement needed

**Comment by rosamoc** [comment]
@markoprljic ok thank you!

**Comment by rosamoc** [comment]
@markoprljic this one? https://tecommons.medium.com/

**Comment by markoprljic** [comment]
No. I meant forum https://forum.tecommons.org/

**Comment by rosamoc** [comment]
@markoprljic OK thanks

**Comment by markoprljic** [comment]
@rosamoc We have a question regarding email newsletter setup, can you give your feedback here? https://github.com/commons-stack/iteration0/issues/565 

Thanks!

**Comment by rosamoc** [comment]
@markoprljic You can now visit the page (It is not open to everyone) . The newsletter section is not yet available. But in the meantime you can check it out and give your opinion. I tried to make it as close to your design as possible, but a screen is not the same as a fixed design.
https://tecommons.org/?page_id=380

**Comment by markoprljic** [comment]
Thanks Rosa. So far so good, just a couple of things:

- please make the background full width
- Buttons seem to be images, can we make them with CSS?
- would you be able to style all Headings with CSS instead of images?
- can you replace the Favicon with one from the [branding repo](https://github.com/TECommons/tec-branding-assets/tree/main/Logo)?

Thanks.

**Comment by rosamoc** [comment]
@markoprljic  
Yes. One question,  the background do you mean the black one? Not boxed? Full width?

**Comment by markoprljic** [comment]
Not boxed, full width please

**Comment by rosamoc** [comment]
@markoprljic Done!

**Comment by markoprljic** [comment]
@rosamoc LOOKING GREAT! WOOOHOOOO! Thanks a ton! :)))

One little thing, not sure if you had trouble with it ... in the footer Submit button can you make it white button so It stands out?

Other than that this is great! Ready to go live IMO

**Comment by rosamoc** [comment]
@markoprljic No, no, just a little more work to do it but not impossible, I'm going to do it. ;-)

**Comment by markoprljic** [comment]
🤗

**Comment by rosamoc** [comment]
@markoprljic Done!! When you think it is ready, I will publish it

**Comment by markoprljic** [comment]
Looking good! Now ... getting into the nitty-gritty :D
We're having our weekly sync today at 6PM CET, I'd love you to join :)

Main navigation alignment:

![Image 2021-03-02 at 11 22 57 am](https://user-images.githubusercontent.com/5704285/109634658-c6055780-7b49-11eb-8cab-3ee72f9362c9.jpg)


Footer adjustments:

![Image 2021-03-02 at 11 17 15 am](https://user-images.githubusercontent.com/5704285/109634515-9e15f400-7b49-11eb-8070-dcadbfa56e3e.jpg)

**Comment by rosamoc** [comment]
@markoprljic OK perfect! I'll be there, but I'll have to go a little earlier. Thank you! See you there!

**Comment by markoprljic** [comment]
@rosamoc Did you test the Hubspot integration, subscribe to newsletter is sending emails to our Hubspot account? 
@knobsdao Can you please check as well? I tried logging in to Hubspot but need the code sent to email and I didn't have access to it. Thanks.

**Comment by rosamoc** [comment]
@markoprljic It's not working, I'm going to fix it.

**Comment by knobsdao** [comment]
@markoprljic @rosamoc I'll be mindful of/watching the HubSpot. There's an option to add other team members - right now there's only the one tied to the TEC gmail but could add more if you want (this will also useful for comms to test email campaigns going forward, etc.).

**Comment by rosamoc** [comment]
@markoprljic I have already made the modifications to the design

**Comment by markoprljic** [comment]
Perfect! Thank you very very very many much @rosamoc This issue is closed! Yeeeeeee! :)
