### ISSUE TITLE
SEO, Metadata and Integrations settings in Wordpress

### ISSUE THREAD

**Issue by markoprljic** [TECommons/coordination#325]
Related to Issue #428

**Comment by markoprljic** [comment]
There is a [HubSpot WordPress plugin](https://www.hubspot.com/products/wordpress) that may be useful.

**Comment by markoprljic** [comment]
[Related issue (closed)](https://github.com/TECommons/coordination/issues/165) regarding Hubspot and Substack.
@rosamoc

**Comment by markoprljic** [comment]
Hi Rosa, just wanted to check in on the SEO tags that you and Edu have been working on. You do have a list of those?
This is related to the website and possibly setting up the SEO plugin and settings inside the WP theme. 
Do you have everything you need to set it up?

**Comment by rosamoc** [comment]
@markoprljic  We agreed with Edu that a first list of keywords would be made (not made by me but by the people who write the contents) and that later I would review it to see the most searched words in google. Then this list would be sent to everyone for review and final OK.
For now I have not received any list....

**Comment by markoprljic** [comment]
Thank you very much for the clarification Rosa.

@eduardovegap Sorry if I missed it, but where can we find the SEO keywords list? Has it been approved? Thanks.

**Comment by eduardovegap** [comment]
> @markoprljic We agreed with Edu that a first list of keywords would be made (not made by me but by the people who write the contents) and that later I would review it to see the most searched words in google. Then this list would be sent to everyone for review and final OK.
> For now I have not received any list....

¡Hey there Rosa! 

I sent it to you through Telegram, but the two ticks aren't checked, let me know if you didn't receive them on our conversation to resend it!

**Comment by rosamoc** [comment]
Yes, I just read it.

**Comment by rosamoc** [comment]
Thank you!

**Comment by markoprljic** [comment]
@rosamoc Since the website is almost done, did you also include any SEO plugins and added the keywords from Eduardo?

**Comment by rosamoc** [comment]
@markoprljic Not yet, next step
