### ISSUE TITLE
Audit / Add proposal for vote on the forum

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#329]
Create a transparency audit proposal and post in the forum to gather votes

**Comment by iviangita** [comment]
Posted under the Advice Process category for feedback before we proceed with Forum Voting: 
https://forum.tecommons.org/t/transparency-audit-proposal/221

**Comment by Zeptimus** [comment]
https://forum.tecommons.org/t/tec-transparency-audit-proposal/235 :-D
