### ISSUE TITLE
Audit / Define the Transparency Audit criteria and design the process

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#330]
Doing this async then schedule a working sesh to compare/combine our criteria and discuss with other stewards

**Comment by iviangita** [comment]
Done! The [criteria](https://docs.google.com/document/d/1qL5rOJLFF7UsioslmdZwbf6-o3jDUPaxaBtGSGhjVJQ/edit) is ready for posting in the forum :)

**Comment by Zeptimus** [comment]
We are re-opening it to for on the funding section.

**Comment by Zeptimus** [comment]
Close, https://docs.google.com/spreadsheets/d/1P2hbPZwdNHRfKXjz6_3iJss2e2-0KeojTu8QPuLb19s/edit#gid=236417183

**Comment by Zeptimus** [comment]
Close, https://docs.google.com/spreadsheets/d/1P2hbPZwdNHRfKXjz6_3iJss2e2-0KeojTu8QPuLb19s/edit#gid=236417183
