### ISSUE TITLE
Audit / Test the audit on handful of WGs

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#331]

**Comment by Zeptimus** [comment]
We will reach out to Soft Gov @liviade1  and Gravity @JuankBell to discuss the details and their availability.

**Comment by iviangita** [comment]
UPDATE from the Stewards Call: @eduardovegap and @JuankBell volunteered to participate in the trial audit. :D

**Comment by Zeptimus** [comment]
Update: We gather feedback from Hatchers putreach, Gravity and Soft Gov. Thanks guys
