### ISSUE TITLE
Gardens Swarm Manifesto for 1hive

### ISSUE THREAD

**Issue by iviangita** [TECommons/coordination#332]
## 📋 Anything to add?
Draft the Gardens Swarm Manifesto that's geared towards 1hive

## 🎉 Subtasks

- [ ] Interview Sem
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@GriffGreen 
@sembrestels 

## 🔗 Work doc - inspirational links
Reference: https://docs.google.com/document/d/1-CY39HVgHcpRFac10FME97pqPclHMrj2YsphOGYUDm8/edit

**Comment by GriffGreen** [comment]
You are the best Ivy! Thx!

**Comment by iviangita** [comment]
Moving this to Gardens Swarm Workspace [issue 27](https://app.zenhub.com/workspaces/garden-swarm-workspace-5fe322aef3aab0001be1d518/issues/tecommons/tec-ui/27)
