### ISSUE TITLE
TEC WG Agenda template 

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#337]
## 📋 Anything to add?

Create a TEC Agendas template that the Stewards can use in their Working Groups.
Include these and other elements that are required or nice to have :
-Transparency WG disclaimer (required)
-Attendees
-TEC logo
- Date
-Agenda
-etc....

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

## 🔗 Work doc - inspirational links
[TEC WG Agenda Template](https://docs.google.com/document/d/1T0FDc6d7T-GP9CEitCLOIRdo7Tfpd3Bq0JdoL0D5wbc/edit#heading=h.h8sh4jgt65od)

**Comment by iviangita** [comment]
Done!
