### ISSUE TITLE
Figure out the blockers for what is stoping the Commons Stack Association from being ready 

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#34]
## 📋   Anything to add?

CSTK Tokens are critical for the TEC but the Commons Stack has a few blockers to finishing the task... they need to be defined and then tackled so we can launch!

## 🎉   Subtasks

- [ ] Look thru the Commons Stack github and identify the issues that need help
- [ ] Make an issues here to track the blocking Commons Stack issues

## 🤼‍♂️   Reviewer

@lorelei1

## 🔗   Work doc - inspirational links
https://github.com/commons-stack/iteration0/issues?q=is%3Aopen

**Comment by drllau** [comment]
The fact that hatchers have no [formal vote ](https://www.canva.com/design/DAEOXnY9VGA/T9rgwhirQ9spmYyLRTPa4A/view?utm_content=DAEOXnY9VGA&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton) in CommonsStack even though dues are demanded. In the event that the hatch is aborted after funds raised, there is no recourse to exit.

**Comment by GriffGreen** [comment]
Setting up the email
Setting up the T&Cs
Setting up the Statutes
Setting up the Campaign
