### ISSUE TITLE
TBC Proposal / Badger DAO. 

### ISSUE THREAD

**Issue by eduardovegap** [TECommons/coordination#348]

**Comment by tamarandom** [comment]
Hey @freedumbs00! You're on this, right? @eduardovegap and I are using the same assignments as were on the tec_curate xls.

**Comment by freedumbs00** [comment]
Yes I am but it shouldnt be onboarding.  This should have its own issue

**Comment by freedumbs00** [comment]
BadgerDao will not be making a proposal.  They're better as potential Hatchers.
