### ISSUE TITLE
TBC Proposal / Balancer cadCAD models. 

### ISSUE THREAD

**Issue by eduardovegap** [TECommons/coordination#349]

**Comment by freedumbs00** [comment]
Made contact with Balancer and team that is building a cadCad model for them.  Will be directing them towards YGG and our proposal process.

**Comment by freedumbs00** [comment]
Angela is heading the balancer cadCad.  Upon speaking with her she decided to make proposal for TE instead and not balancer.  She will be submitting within the next few weeks.   Closing issue.
