### ISSUE TITLE
TBC Proposal / Conflux. 

### ISSUE THREAD

**Issue by eduardovegap** [TECommons/coordination#350]

**Comment by tamarandom** [comment]
Hey @jessicazartler ! You and @Jeff-Emmett are on this one (from the curate sheet). Drop any updates here as they come.

**Comment by jessicazartler** [comment]
Have a call with them next week, I don't think they will submit.. but will circle back

**Comment by jessicazartler** [comment]
They will not be submitting, they have their own funding streams & grants program
