### ISSUE TITLE
Meeting attendance terms

### ISSUE THREAD

**Issue by Santigs** [TECommons/coordination#371]
## 📋 Anything to add?
Discuss Terms in Legal WG to see if additional actions are required
https://docs.google.com/document/d/1T0FDc6d7T-GP9CEitCLOIRdo7Tfpd3Bq0JdoL0D5wbc/edit#

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by tamarandom** [comment]
@iviangita and @Zeptimus as FYI as you're all working on this together.

**Comment by iviangita** [comment]
Quick update: draft in progress :) 

Here's the link to the doc for our common reference: https://docs.google.com/document/d/1-ysqAIbqx4KY3WEiVqnX8SUVC8197cKiFdxJSWOjgLc/edit#

We'll notify Santi once it's ready for review :)

**Comment by iviangita** [comment]
Hi @Santigs, we're handing over the [meeting attendance terms](https://docs.google.com/document/d/1-ysqAIbqx4KY3WEiVqnX8SUVC8197cKiFdxJSWOjgLc/edit#) to you - we've made a few changes based on our last meeting. Adrian also added his inputs and comments - for your final review/touch and approval please. :)

cc: @Zeptimus

**Comment by Santigs** [comment]
Perfect, I will ask Ricardo to take a look and may also include Shawn if he joins us in this week meeting,

**Comment by tamarandom** [comment]
Update : completed.
