### ISSUE TITLE
Draft up a "How to Propose TEC Hatch DAO Params" forum post

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#373]
## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by freedumbs00** [comment]
@GriffGreen   Are we sure this is still the direction we want to take?  I know people will use the site and play with the sliders and use tokenlog and vote but how many people are actually going to create parameters and submit issues?

**Comment by freedumbs00** [comment]
This is becoming a "How to video" on How to Propose TEC Hatch Dao Params

**Comment by tamarandom** [comment]
@freedumbs00 Nice! Do we pull this into the next Sprint?

**Comment by freedumbs00** [comment]
Yeah

**Comment by freedumbs00** [comment]
https://docs.google.com/document/d/1szNUKI7O89yA4vKpfLC_eEMozIJZJZBpUAz6Y4hARL8/edit#

Closing issue
