### ISSUE TITLE
add the COC to the TEC Gitbook 

### ISSUE THREAD

**Issue by liviade1** [TECommons/coordination#376]
## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by liviade1** [comment]
We got a free subscription :D click here to enter the team as a writer 
https://app.gitbook.com/invite/token-engineering-commons?invite=-MRe_ELNPr23yao7rvcs

**Comment by markoprljic** [comment]
@liviade1 Would you be interested to get help from @divine-comedian on writing and updating the documentation of our TEC Gitbook? 
Also, @divine-comedian please look around https://app.gitbook.com/invite/token-engineering-commons?invite=-MRe_ELNPr23yao7rvcs and let us know if you have ideas where you could contribute.

Thanks.
