### ISSUE TITLE
New discord server : feedback from Angela on best way to approach this 

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#378]
## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by metaverde** [comment]
So is the migration in this sprint?
My Discord froze as soon as I asked about it, of course.

**Comment by jessicazartler** [comment]
Just this issue for me to talk with Angela, but we do need someone to support in the migration and switching to the new discord. Are you interested to support that? Thanks so much MetaVerde!

**Comment by tamarandom** [comment]
Hey @metaverde ! The discord migration itself isn't in this Sprint. This piece of work is @jessicazartler laying the groundwork so that the transition goes smoothly.

Designing the onboarding journey, taking inspiration from the great way 1Hive does theirs, is in this Sprint. It's #303 and could benefit from your knowledge.

**Comment by markoprljic** [comment]
@jessicazartler Can we move this issue In Progress?

**Comment by jessicazartler** [comment]
Yes, we can close it actually. 

I had a call with Angela this morning, she supports us migrating to a new TEC discord, she just asked to be in the loop on when and how it is happening. I suggest adding her to the migrate Discord Github issue as reviewer so she can see it unfold and discussions there. 

The only one concern she had was having continued support for Discord, she will speak with Kay to ask for continued help going forward and I told her just ask if she needs a contributor to support and we can put a call out. 

@markoprljic if you can double check if Angela is on TEC github board and add her as reviewer to any migrate to new discord issues - thank you!

**Comment by markoprljic** [comment]
Will do.
