### ISSUE TITLE
Hand off the recurring Tweets to Ivy/Shawn

### ISSUE THREAD

**Issue by jessicazartler** [TECommons/coordination#383]
## 📋 Anything to add?

I am handing off the weekly recurring Tweets to Ivy -- community calls/TEC labs/other scheduled repeating Tweets from this issue https://github.com/TECommons/coordination/issues/382

## 🤼‍ Reviewer

@iviangita @markoprljic @tamarandom

**Comment by jessicazartler** [comment]
Had a call with Ivy this morning to walk through recurring Tweets and scheduled them for this week.. Ivy will start with a Graviton reminder tweet for Thursday, sort her permissions and we will have a follow up call next week where she will schedule the Tweets for next week, and we'll go over any questions that come up :D So after that call we'll be fully handed off, and just coordinate any questions over Telegram -- thank you again @iviangita for taking this on - you are a superstar!

**Comment by markoprljic** [comment]
Needs another meeting with @jessicazartler to complete this task. Target before Sprint Retro.

**Comment by jessicazartler** [comment]
Had 2nd meeting this morning - all good moving forward, will coordinate with Ivy if I need anything further or add to the weekly Tweet document closing :D
