### ISSUE TITLE
Digital Security Management

### ISSUE THREAD

**Issue by jessicazartler** [TECommons/coordination#384]
## 📋 Anything to add?

We need an audit, process for sign ins/account/permission and data management to decide who has access to different accounts, when we hand them out, and tracking who has what permissions. Understanding any potential legal issues (Kris) what we are responsible for in the TEC to handle this, etc. and an owner who is responsible/accountable for this.

Commons Stack went through something similar - you can look at this issue for some guidance https://github.com/commons-stack/iteration0/issues/249

But we may not have to be as strict as we are dencentralized, that is a Kris/Griff question -- but this is important going forward as we are starting up a CRM and will be handling personal information/emails etc. getting ready for the hatch

## 🤼‍ Reviewer

@tamarandom @GriffGreen @Zeptimus @cranders1 @jessicazartler @krisjpi

**Comment by markoprljic** [comment]
@Zeptimus signaling support from Transparency WG.

**Comment by tamarandom** [comment]
This is something @krisjpi has planned for CS.

**Comment by markoprljic** [comment]
@krisjpi @Zeptimus Hi guys, can one of you assist and help with this task? If you know someone else who can contribute please suggest.

**Comment by markoprljic** [comment]
@Zeptimus You said you did some research already, how far did you come and where did you hit the wall?

**Comment by markoprljic** [comment]
The outcome of the planning session with Zepti:

- We will create a Secret Wiki which will hold a list of all credentials incl. the list of people who have access to the Secret Wiki itself
- @Zeptimus  is the gatekeeper and maintainer of the Secret Wiki
- New members who need limited access to certain platforms will be given permissions on the application level (i.e. create a user  with limited permissions or powers etc.)
- Discord admin powers will be given to the head moderator @JuankBell. All other powers will be later regulated through Discord roles

All community members who hold the keys to anything we're using at the moment please provide that information to @Zeptimus 

Thank you.

**Comment by jessicazartler** [comment]
NICE! Thanks guys!!!

**Comment by markoprljic** [comment]
@Zeptimus Hi man! :) What's the status of this issue? How are we doing?

**Comment by Zeptimus** [comment]
All the information i know its writed, would be cool to add at least 2 or 3 members more as owner in the app so more people can manage it if something happen to me :D. Im lacking information about TEC medium to close this issue

**Comment by markoprljic** [comment]
Awesome!

Please add @GriffGreen @tamarandom and myself as the owners.

**Comment by Zeptimus** [comment]
I need keybase handle, email adress or phone number maybe you guys can send me on telegram any of those and i invite you

**Comment by tamarandom** [comment]
⚡️ Sent in TG ⚡️
