### ISSUE TITLE
Help Wanted : Legal experts

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#387]
## 📋 Anything to add?

Calling all contributors with legal experience :  The TEC is looking for additional support in our Legal Working Group! 

Reach out to @Santigs, Legal WG Steward, or join the call on our discord voice channel Legal-TEC every Friday at 4pm CET.

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by tamarandom** [comment]
Done!

**Comment by iviangita** [comment]
This one is related to [Issue 388](https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/tecommons/coordination/388), which we closed already. Checking with @Santigs if he wants us to re-share the tweet from time to time so I can reopen the issue and label it as a repeating task

**Comment by Santigs** [comment]
Thank you Ivi, no need to reopen by now. It seems we have onboarded two new lawyers into the WG

**Comment by iviangita** [comment]
@Santigs great, thanks! Closing :)

**Comment by tamarandom** [comment]
> Thank you Ivi, no need to reopen by now. It seems we have onboarded two new lawyers into the WG

ALLLLLLL RIGHT!!! Excellent ! 🙌🏽
