### ISSUE TITLE
Twitter share Legal WG need for legal expertise 

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#388]
## 📋 Anything to add?

The idea is to get reach on a call for legal contributors in the Legal WG. A message in a bottle thrown into the twitter sea. Something along the lines of, "Have you a legal background and a fascination with decentralized technologies? The TEC has a Legal WG that needs someone exactly like you to xyx. Contact us here abc." but written much better and approved by @Santigs.

## ❓ Why is it important?

To represent Legal WG in comms.

## 🎉 Subtasks

- [x] @iviangita include this in the planning doc https://docs.google.com/document/d/1Sf9p05e8rjeUZaFFrjoRPmUOdTJcb8sk7xhK3UC8rNw/edit#heading=h.e7h7xsy4jgxt
- [x] @Santigs Review doc and proposed tweets from Ivy

## 🤼‍ Reviewer

@Santigs @iviangita

**Comment by markoprljic** [comment]
@tamarandom I may be missing the context here. Can you elaborate more?

**Comment by tamarandom** [comment]
Sure. ;)

The idea is to get reach on a call for legal contributors in the Legal WG. A message in a bottle thrown into the twitter sea. Something along the lines of, "Have you a legal background and a fascination with decentralized technologies? The TEC has a Legal WG that needs someone exactly like you to xyx. Contact us here abc." but written much better and approved by @Santigs.

**Comment by markoprljic** [comment]
Got it now, thanks 😊

**Comment by iviangita** [comment]
Hi @tamarandom @Santigs, below is the copy I drafted. Hope you can review and let me know if there's anything you want to change. :) 

P.S. Twitter has 280 character limit. If more details need to be added, I suggest to put them in a nice graphic instead. 

"OPEN CALL FOR LEGAL EXPERTS: Do you have a legal background and strong interest in decentralized technologies? We'd love you in our Legal WG! Your expertise will be a huge help in shaping our legal strategies. If interested, please contact our Legal Steward @santigs.🙏"

**Comment by tamarandom** [comment]
Hey @iviangita Looks good to me.

**Comment by markoprljic** [comment]
Need feedback from @Santigs to complete this task and close issue.

**Comment by Santigs** [comment]
Looks good to me too guys.
Thank you @iviangita for writing it and @tamarandom and @markoprljic for reviewing it!

**Comment by iviangita** [comment]
Posted w/ Jess' edits! Here's the [tweet](https://twitter.com/tecmns/status/1356265609869189128?s=20). :)

Closing now :)
