### ISSUE TITLE
Define the TEC One-liner

### ISSUE THREAD

**Issue by markoprljic** [TECommons/coordination#389]
## 📋 Anything to add?

Define the tagline, one-liner for TEC

## 🔗 Work doc - inspirational links

https://docs.google.com/document/d/1VOM39PVE41_GYKUbdZCZIu_xySDp60tLTXqup2-t27I/edit#heading=h.rqn94la2893x

https://miro.com/app/board/o9J_kjDw5AE=/
TokenEngineering

**Comment by jessicazartler** [comment]
Accelerating‌ ‌Sustainable‌ ‌&‌ ‌Ethical‌ ‌Design‌ ‌for‌ ‌Token‌ ‌Ecosystems‌ ‌🥳🏓 for now :D
