### ISSUE TITLE
Investigate dxDAO

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#39]
## 📋   Anything to add?

Ideally, all the the notes would be collected in this issue. 

## 🎉   Subtasks

- [ ] Research their documents
- [ ] Make a list of questions
- [ ] Schedule a call with someone familiar with their legal strategy, ideally their legal lead (Griff might be able to help)
- [ ] Take notes on the call and post them in this issue
- [ ] Create lots of new issues that the legal working group need to consider that derive from this research

## 🤼‍♂️   Reviewer

@Santigs

**Comment by GriffGreen** [comment]
Assigned to Marina!

**Comment by GriffGreen** [comment]
DXdao is freezing their bonding curve?!?!?!?

**Comment by GriffGreen** [comment]
https://medium.com/@rawsonpatrick/the-first-ever-blockchain-native-entity-has-made-history-raising-funds-in-a-completely-a1b36e871af6

DXdao has no legal entity.

**Comment by tamarandom** [comment]
Closing!
