### ISSUE TITLE
Praise Quant / News Blog: Jan. 15 - Feb. 1

### ISSUE THREAD

**Issue by jessicazartler** [TECommons/coordination#392]
## 📋 Anything to add?

Bi-weekly praise & news blog

## 🎉 Subtasks

- [x] Jess create draft w/ big news headlines
- [x] Craig write & publish
- [x] Jess distribute

## 🤼‍ Reviewer

@GriffGreen 

## 🔗 Work doc - inspirational links
https://docs.google.com/document/d/1bOzENvd5kjEOEBfGryurm12uguikViBT2xGnTjsX6F4/edit

**Comment by jessicazartler** [comment]
@cranders1 draft is ready :D

**Comment by cranders1** [comment]
Hey @jessicazartler @GriffGreen - PQ blog ready for revision & link check

**Comment by jessicazartler** [comment]
on it now will let you know when I finish

**Comment by jessicazartler** [comment]
@cranders1 finished - just a few tiny things but DAMN this blog looks gooooood! Fantastic, I really love your writing and creative expression - beauty! Let me know when you publish and I'll get on distribution - thank you so much for your awesome work!

**Comment by cranders1** [comment]
done. saw you already in there cleaning it up. much thnx.

**Comment by GriffGreen** [comment]
Looks great! @jessicazartler  @cranders1 I sent the higher res IH lists directly to craig
i hope they get used over the ones in the google doc :-D

**Comment by cranders1** [comment]
Original images inserted

**Comment by jessicazartler** [comment]
https://twitter.com/tecmns/status/1357331827178971141
Bump, set, spike! Nice job team!! @cranders1 @iviangita
