### ISSUE TITLE
Hatch Outreach WG : Continue FAQ based on the feedback from onboarding active community members 

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#395]
## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by tamarandom** [comment]
The FAQ will inform the TEC Hatch article. Priority bumped up.

**Comment by tamarandom** [comment]
It's still a WIP but @GriffGreen did a good amount of work on adding to it already! 
https://docs.google.com/document/d/16FYhIodALP2tDldtuxuDbg-3Q4E7llgSatdlhHO6Sos/edit#

**Comment by tamarandom** [comment]
Hey @eduardovegap!  @natenatesoo's work on the FAQ is shaping up nicely : https://docs.google.com/document/d/16UI-EfD4qcwBaAv3Eexlv01SOK7oiDt4gkVT5rEY6X4/edit#

**Comment by tamarandom** [comment]
Great work @natenatesoo and @eduardovegap !! Closing!

**Comment by GriffGreen** [comment]
I'm still working on this! Major break thru on the Trusted Seed framing that I want to get out:

Main point: The Trusted Seed is all we need to talk about... to be a member of the Trusted Seed you have to join the Legal entity... and we really don't have to talk about the Commons Stack Association... thats like the Trusted Seed's Slave Name.

**Comment by natenatesoo** [comment]
Lol.  Sounds good! I'll work on rephrasing some of the answers that omit the Trusted Seeds government name.  Also, what is the best vehicle for this FAQ?  Will we have a website going up, or should we try to incorporate it within the TEC Handbook?  Blog Post?

**Comment by tamarandom** [comment]
Update : Magic happening here  https://app.gitbook.com/@token-engineering-commons/s/tec-handbook/hatch-101/welcome-hatchers

**Comment by tamarandom** [comment]
Update : Closing.
