### ISSUE TITLE
We need more MEMES

### ISSUE THREAD

**Issue by markoprljic** [TECommons/coordination#396]
## 📋 Anything to add?

Dedicated Time for Team Meme Production
Meme party Fridays / new Discord has meme channel
make a meme for the AMA call :D
make memes as I go and not plan

## 🤼‍ Reviewer

@freedumbs00

**Comment by markoprljic** [comment]
There's already an issue for this https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/tecommons/coordination/397

**Comment by markoprljic** [comment]
@freedumbs00 Can we do an Uncle Sam "we need you" meme for our call to join TEC? https://memegenerator.net/instance/70384764/uncle-sam-we-need-you

You da man for that stuff. Wanna do it? :)

**Comment by tamarandom** [comment]
@freedumbs00 You're AWESOME. Closing. ;)
