### ISSUE TITLE
Investigate DIA

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#40]
## 📋   Anything to add?

Ideally, all the the notes would be collected in this issue. 

## 🎉   Subtasks

- [ ] Research their documents
- [ ] Make a list of questions
- [ ] Schedule a call with someone familiar with their legal strategy, ideally their legal lead (Griff might be able to help)
- [ ] Take notes on the call and post them in this issue
- [ ] Create lots of new issues that the legal working group need to consider that derive from this research

## 🤼‍♂️   Reviewer

@Santigs 

## 🔗   Work doc - inspirational links

**Comment by tamarandom** [comment]
Closing!
