### ISSUE TITLE
Santi / TEC Stewards Apply for Swiss Membership (Details in the Epic!)

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#400]

**Comment by Santigs** [comment]
Trying this weekend.
First transaction whent through but experiencing problems with the second.
Still waiting

https://github.com/commons-stack/tech-dapp/issues/181

**Comment by tamarandom** [comment]
Thanks @Santigs This is super helpful. Looking into it! Will you let me/us know if/when the tx completes.

**Comment by Santigs** [comment]
Finally, the transaction went through!
I got the Thank you email from Giveth.
![Screenshot 2021-02-21 at 08 20 44](https://user-images.githubusercontent.com/34634436/108618362-b4bb9d00-741d-11eb-8d79-457eb7be23a5.png)

**Comment by tamarandom** [comment]
Excellent! Welcome to the Association!! 
I'll close this issue and the one in the Swiss Asso. dApp repository!
