### ISSUE TITLE
Rename the Onboarding WG

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#409]
## 📋 Anything to add?

The name Onboarding makes people think this is where new community members are being onboarded into the TEC. This is not the case. The Onboarding WG is actually onboarding Hatchers and Projects. 

Renaming this group will cause a lot less confusion. 

(Added to the Community Stewards Agenda for discussion).

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by eduardovegap** [comment]
This has been accomplished.
