### ISSUE TITLE
Investigate Fairmint

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#41]
## 📋   Anything to add?

Ideally, all the the notes would be collected in this issue. 

## 🎉   Subtasks

- [ ] Research their documents
- [ ] Make a list of questions
- [ ] Schedule a call with someone familiar with their legal strategy, ideally their legal lead (Griff might be able to help)
- [ ] Take notes on the call and post them in this issue
- [ ] Create lots of new issues that the legal working group need to consider that derive from this research

## 🤼‍♂️   Reviewer

@Santigs 

## 🔗   Work doc - inspirational links

**Comment by drllau** [comment]
[Article](https://notboring.substack.com/p/fairmint) but doesn't go into their continuous agreement for future equity ([CAFE](https://fairmint.co/cafe-continuous-agreement-for-future-equity/)).
![image](https://user-images.githubusercontent.com/14944510/99741752-f4b47080-2b0c-11eb-84c5-65bc578c83d9.png)

**Comment by tamarandom** [comment]
Closing!
