### ISSUE TITLE
Gravity Trial Audit

### ISSUE THREAD

**Issue by Zeptimus** [TECommons/coordination#410]
## 📋 Anything to add?

@Zeptimus and @iviangita will prepare the documentation and contact @JuankBell to work on it

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by JuankBell** [comment]
Yes!

**Comment by Zeptimus** [comment]
Close, thanks Juan :)
