### ISSUE TITLE
Add meeting T&C's to the Discord T&C's

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#411]
## 📋 Anything to add?

https://docs.google.com/document/d/1-ysqAIbqx4KY3WEiVqnX8SUVC8197cKiFdxJSWOjgLc/edit#

I don't have the discord terms link...

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by JuankBell** [comment]
Discord terms Link: https://docs.google.com/document/d/1NTp3KT20iNbVL2VvcZNusXtSnejIXwtyCXOA1cXaVIA/edit

**Comment by markoprljic** [comment]
I think this has been added to Discord to rules-must-check channel. @Zeptimus I believe you can close it.

**Comment by Zeptimus** [comment]
Yes sry, Close!
