### ISSUE TITLE
Hatcher Outreach Trial Audit

### ISSUE THREAD

**Issue by Zeptimus** [TECommons/coordination#412]
## 📋 Anything to add?

@iviangita and @Zeptimus will prepare the documentation and contact @eduardovegap 

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by Zeptimus** [comment]
Note: Add feedback on the comment section

**Comment by eduardovegap** [comment]
Shall we close this one @Zeptimus?

**Comment by Zeptimus** [comment]
yes! thanks Edu :D
