### ISSUE TITLE
prepare presentation to ETH Denver 

### ISSUE THREAD

**Issue by liviade1** [TECommons/coordination#414]
## 🎉 Subtasks

- [ ] prepare slides
- [ ] get feedback from the stewards 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by liviade1** [comment]
Hey @jessicazartler @tamarandom @Zeptimus @GriffGreen @freedumbs00 @JuankBell @cranders1 @eduardovegap @Santigs @metaverde feel free to drop topics here you think should be in the talk to represent the TEC in the best way possible 🙏

**Comment by GriffGreen** [comment]
Your Economy Your Choice... show off the dandelion voting chart... its so fucking coool!!

The importance of a Cultural build

The role of Commons Stack 

Emphasize The IDENTITY of the TEC

Meme the fuck out of the slides

**Comment by jessicazartler** [comment]
You can use stuff from the website content doc as it is all the best phrasing distilled
https://docs.google.com/document/d/1VOM39PVE41_GYKUbdZCZIu_xySDp60tLTXqup2-t27I/edit#

+ the Jake meme pinned on Twitter

Let me know if you want to bounce any ideas or need a second pair of eyes when you are finished - good luck - you got this! :D

**Comment by cranders1** [comment]
Awesome Livi. Will ponder and provide feedback. Attending sessions will help stimulate creativity. Looking forward to your talk.

**Comment by Zeptimus** [comment]
I would talk about the Commons book and the rules and boundaries we are trying to implement that are based on elionor's research. And I would add slides with a picture of us celebrating any event like praise, giving or cagatio to show that we together and know to have fun.

**Comment by JuankBell** [comment]
Invite people to the Graviton trainings :D
