### ISSUE TITLE
Investigate Investment Clubs

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#42]
## 📋   Anything to add?

Ideally, all the the notes would be collected in this issue. 

## 🎉   Subtasks

- [ ] Research their documents
- [ ] Make a list of questions
- [ ] Schedule a call with someone familiar with their legal strategy, ideally their legal lead (Griff might be able to help)
- [ ] Take notes on the call and post them in this issue
- [ ] Create lots of new issues that the legal working group need to consider that derive from this research

## 🤼‍♂️   Reviewer

@Santigs 

## 🔗   Work doc - inspirational links

https://www.sec.gov/reportspubs/investor-publications/investorpubsinvclubhtm.html

**Comment by GriffGreen** [comment]
https://www.sec.gov/reportspubs/investor-publications/investorpubsinvclubhtm.html

**Comment by drllau** [comment]
See also ASIC [definition ](https://asic.gov.au/regulatory-resources/digital-transformation/initial-coin-offerings-and-crypto-assets/#part-f)of investment [scheme](https://asic.gov.au/for-finance-professionals/managed-investment-scheme-operators/starting-a-managed-investments-scheme/what-is-a-managed-investment-scheme/)
