### ISSUE TITLE
Tokenlog problem cannot vote

### ISSUE THREAD

**Issue by markoprljic** [TECommons/coordination#420]
## 📋 Anything to add?

Connected with wallet on xDAI
Wallet has IHT
Click to Vote on Tokenlog
Vote button is disabled
Cannot add more votes and vote

![Image 2021-02-05 at 6.22.10 pm.png](https://images.zenhubusercontent.com/5cc090818b624e26c3734d75/034e8083-7200-4634-a9cb-4ce732d5980c)

## ❓ Why is it important?

Cannot vote!

## 🤼‍ Reviewer

@freedumbs00

**Comment by freedumbs00** [comment]
Submitted to Tokenlog github and  @wslyvh

**Comment by wslyvh** [comment]
It's closed already? Is it resolved, or what was the problem?
