### ISSUE TITLE
source cred hack session 

### ISSUE THREAD

**Issue by liviade1** [TECommons/coordination#427]
## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@liviade1 @Santigs 

## 🔗 Work doc - inspirational links
https://docs.google.com/document/d/1mp5W2hDsdYw-PiFY49ohafE7GVyfLSMewZphEZ7mrcM/edit

**Comment by liviade1** [comment]
Hey @Santigs @mateodaza I thought friday would work but it's a little tight for me. 
Can we schedule a session for monday? I'm free anytime between 2 and 5 pm CET

**Comment by Santigs** [comment]
Monday 4pm works for me

**Comment by tamarandom** [comment]
Hey @mateodaza ! This was yesterday and today, right? Can we close this one?

**Comment by tamarandom** [comment]
Closing! We can have another hack sesh is needed.
