### ISSUE TITLE
Define SEO Keywords and hashtags

### ISSUE THREAD

**Issue by markoprljic** [TECommons/coordination#428]
We want to start with 10 to 15 keywords and then she would refine that list. **The list would be used for all communication channels from youtube titles, to blog titles and hashtags.** 

- Every page of the web would have 2 keywords.
- The list of words should from very general to very specific range.

Also, we need to start sending links to the web, for example if we use the keyword “cryptoeconomics” on the forum/blog/medium we should link back to the section of the web that mentions it.

**Comment by eduardovegap** [comment]
@jessicazartler do you wanna do a small session for this?

**Comment by jessicazartler** [comment]
Finished on our call this morning - thank you @eduardovegap !

**Comment by markoprljic** [comment]
@eduardovegap Can we consider this issue done? Can we move it in Review/QA?

**Comment by tamarandom** [comment]
Update : closed
