### ISSUE TITLE
Design new banners for various announcements

### ISSUE THREAD

**Issue by markoprljic** [TECommons/coordination#430]
## 📋 Anything to add?

Old banners
![Image 2021-02-12 at 9.54.54 am.png](https://images.zenhubusercontent.com/5cc090818b624e26c3734d75/20d2ef08-54c2-4a8c-8ce0-d187b0b570c3)

![Image 2021-02-12 at 9.55.02 am.png](https://images.zenhubusercontent.com/5cc090818b624e26c3734d75/1999667f-e46f-4743-bfa5-c5f30df5fd4b)

## ❓ Why is it important?

Consistency with new brand and website.

## 🤼‍ Reviewer

@jessicazartler @freedumbs00

**Comment by markoprljic** [comment]
New banners
![Image 2021-02-12 at 3.31.08 pm.png](https://images.zenhubusercontent.com/5cc090818b624e26c3734d75/b1835785-2526-415b-80c2-7197df3c9185)

**Comment by jessicazartler** [comment]
These look AWESOME! So crisp and amazing!!!

Just one request for an edit -- can we stick with warped universe/NFT and remove the sacred geometry? Love geometry but don't think it fits.. thank you so much - love them! Lemme know where the templates lives when its finalized so I can share it with stewards - thank you!!!!

**Comment by freedumbs00** [comment]
I think its important moving forward.  Its what we want to see later.  Kind of an interlude or good foreshadowing.

**Comment by markoprljic** [comment]
Those are part of the wg subbrands. Have you seen them? I'd keep them as such and for announcement banners it's optional.

**Comment by jessicazartler** [comment]
Cool sounds good! Now that I saw the whole story, I like it! :D When should we start using these? Thank you! Nice work!!

**Comment by jessicazartler** [comment]
Where can I access these to start using/sharing around? Thanks!

**Comment by markoprljic** [comment]
@jessicazartler This is related to the issue #431 which is going to be done in the next sprint. Stay tuned!

**Comment by jessicazartler** [comment]
Awesome thank you!
