### ISSUE TITLE
Make the TEC Identity PERVASIVE

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#436]
## 📋 Anything to add?

We had an impromptu identity hack sesh with Chuy, Jake and Tam... and came up with this:

What does the TEC do?

We are `Advancing Token Engineering!`

NEXT STEPS:

Let's run fast with this.... its a great intro for every direction that anyone wants to go...

------
We are `Advancing Token Engineering!`

And TE is more than just tokens, its about building social-economic systems and Gravity is...

------

We are `Advancing Token Engineering!`

The first step is ending the crypto-technocracy, with the TEC params group... 

---------

We are `Advancing Token Engineering!`

We want to build a regenerative professional engineering organization like the IEEE but with an economy that can reward the value being created....

**Comment by markoprljic** [comment]
TEC - Advancing Token Engineering
