### ISSUE TITLE
Find someone to own the administration of the Discord 

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#440]
## 📋 Anything to add?

@metaverde did an incredible job at managing the creation of the discord, now she needs someone to take ownership of it. 

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@metaverde

**Comment by markoprljic** [comment]
@JuankBell Volunteered. 

Juan, can you confirm to take on this task?
