### ISSUE TITLE
VOTE To support the Commons Swarm in getting funding from 1hive

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#447]
https://1hive.org/#/proposal/128

**Comment by GriffGreen** [comment]
@liviade1 @famole @knobsdao @Harthor @cranders1 @ataberkcasur @anthonyoliai @sembrestels @jessicazartler @eduardovegap @mendesfabio @freedumbs00 @iviangita @LinuxIsCool @JuankBell @krisjpi @markoprljic @marthendalnunes @natenatesoo @Zeptimus @Santigs @tamarandom

**Comment by liviade1** [comment]
voted already :))

**Comment by GriffGreen** [comment]
u da best! :-D!!! @liviade1

**Comment by Santigs** [comment]
voted

**Comment by Jeff-Emmett** [comment]
Voted!  Go go commons swarm!

**Comment by jessicazartler** [comment]
Staked yesterday :D Good luck!

**Comment by cranders1** [comment]
done

**Comment by knobsdao** [comment]
🌱🐝

**Comment by tamarandom** [comment]
more done here!

**Comment by famole** [comment]
voted!

**Comment by Vyvy-vi** [comment]
Voted :)
