### ISSUE TITLE
Add to Discord : Meeting attendance terms

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#450]
## 📋 Anything to add?

Ivy, can you pass this document to vyvy-vi when it is final please. 

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by tamarandom** [comment]
Tagging @Vyvy-vi here so you can reach out when the document is final!

**Comment by iviangita** [comment]
Hi @Vyvy-vi, here's the final document :)

https://docs.google.com/document/d/1-ysqAIbqx4KY3WEiVqnX8SUVC8197cKiFdxJSWOjgLc/edit?usp=sharing 

Closing! :D

**Comment by Vyvy-vi** [comment]
![Screenshot 2021-03-02 at 8 50 00 PM](https://user-images.githubusercontent.com/62864373/109713297-09ea7200-7bc7-11eb-8cd5-a16761174d3a.png)
It was added to the rules-! :D
