### ISSUE TITLE
Provide all credentials from our communication channels (social media)

### ISSUE THREAD

**Issue by markoprljic** [TECommons/coordination#456]

**Comment by markoprljic** [comment]
This issue is part of the Digital Security Epic https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/tecommons/coordination/384

We need everyone who has access to any platform to provide credentials to @Zeptimus 
Once you have provided credentials to Zepti please remove yourself as an assignee confirming that you have completed this task.


If you know someone who is not tagged in this issue and should be, please mention that person or add them as an assignee.

Thank you.

**Comment by jessicazartler** [comment]
Wrote @Zeptimus he should have everything from me, I asked him to lmk if he needs any further support on this - thanks Marko!

**Comment by markoprljic** [comment]
@Zeptimus What's the current status of gathering all credentials? What's missing? Who do we need to ask to provide it?

**Comment by Zeptimus** [comment]
We will be using Keybase and its ready to go i'd like to sync with you guys to explain a bit how it works and onboard members

**Comment by markoprljic** [comment]
I believe most of us already use keybase, or used before.

Can you outline here what everyone needs to do do gain access?

**Comment by Zeptimus** [comment]
Keybase handles to invite its enough (work inside keybase still in progress but looking good)

**Comment by markoprljic** [comment]
@Zeptimus Let me know what you received all logins for everything and close the issue. Thanks!

**Comment by markoprljic** [comment]
@jessicazartler Do you know who has Medium credentials? If you do, please direct them to @Zeptimus so that we can close the issue. Thanks!

**Comment by jessicazartler** [comment]
Me and Craig -- I'll DM you Zepti

**Comment by jessicazartler** [comment]
Thanks guys!
