### ISSUE TITLE
New Discord - Transfer admin powers to Juan

### ISSUE THREAD

**Issue by markoprljic** [TECommons/coordination#457]

**Comment by markoprljic** [comment]
@metaverde Please grant admin powers of our new discord to @JuankBell
Thank you.

**Comment by markoprljic** [comment]
Related https://github.com/TECommons/coordination/issues/319#issuecomment-782826830

**Comment by Vyvy-vi** [comment]
I think @metaverde would have to that
(I've got server perms as an Admin but @metaverde is the Server Owner, so they would have to transfer ownership to Juan)
I assigned Juan the `community moderator` role, which is the highest role I can assign(Admin roles are only distributed by the server Owner, I think)

**Comment by markoprljic** [comment]
Thanks for clarification Vyvy. 
@metaverde can you please assist with this? Thanks.
