### ISSUE TITLE
Twitter account management and publishing process

### ISSUE THREAD

**Issue by markoprljic** [TECommons/coordination#459]
## 📋 Anything to add?

We need to decide on the process for publishing on Twitter.
For CS Twitter, Ivy has a weekly twitter plan we keep in excel. It looks like this https://docs.google.com/spreadsheets/d/1QJnratmpodDOuTY-21Lgr6wHr8AK4BOBa-cBI37rHNo/edit#gid=0

We could do the same for TEC. 
Ask Ivy if she can manage the tweets (already has weekly scheduling for TEC tweets)

Who should be responsible for creating content? 
If a community member has a tweet to share where can we send Ivy those tweets to publish? Establish a process and a single place to gather content.

Who will be responsible to tweet/reply/manage our account on a daily basis?

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by jessicazartler** [comment]
I am currently responsible and have already handed off recurring Tweets to Ivy and she is working from this sheet that we did together based on templates I created:
https://docs.google.com/document/d/1Sf9p05e8rjeUZaFFrjoRPmUOdTJcb8sk7xhK3UC8rNw/edit?usp=sharing
See https://github.com/TECommons/coordination/issues/383

In addition to these recurring, I find content from around i.e. memes, inspiring art, articles from stewards/guest blogs etc. and search for RTs and good content that is appropriate from around the ecosystem. 

It can be decentralized further of course - I would recommend anyone wanting to create a Tweet get it edited/approved by at least one other person/second pair of eyes and they can pass to Ivy - or myself if she is asleep - for Tweeting. Happy to discuss on the Comms call further to help document/decentralize the process further, but I do recommend keeping someone at the helm with the context to make appropriate editorial decisions. I am happy to continue with this for some time as I enjoy it :D but I am open to additional process suggestions / improvements

**Comment by markoprljic** [comment]
Grat, thanks @jessicazartler 

So, I assume you and @iviangita can be considered managers for the Twitter publishing?

**Comment by tamarandom** [comment]
Yes! This looks great, @jessicazartler ! 

From my POV you have your finger on the pulse, so to speak, so I'd support you tweeting or retweeting for TEC as long as you enjoy it. Are the other people that tweet from tecmns as well? 

What Ivy has been doing great for CS is the pre-planned calendar (it's a xls so you can look at the full week or full month in one glance - see it here : https://docs.google.com/spreadsheets/d/1QJnratmpodDOuTY-21Lgr6wHr8AK4BOBa-cBI37rHNo/edit?usp=drive_web&ouid=100603646152821457059) 

If we have a way to share ideas or links with her - a channel or document, for example, then she can write the tweet around it. Get it eyeballed and schedule it.

**Comment by markoprljic** [comment]
I assume this issue can be moved to In Review or Close?

**Comment by iviangita** [comment]
I created a Twitter calendar for TEC so we can easily have an overview of the topics/content we will publish for each week. I also added a tab for the wording to be used. Feel free to drop any suggested topics/content as well as the wording. Let me know if there's anything confusing in the calendar so I can improve it. :)

https://docs.google.com/spreadsheets/d/1TEag2jkNqgpFX9oqsqHZ_cQc6UboggIb6Rxctly15fU/edit?usp=sharing

**Comment by markoprljic** [comment]
This is great @iviangita thank you so much. 

Yes, we should definitely share this with everyone, also I'm thinking of a way for people to easily find this sheet to send their suggestions maybe. Considering pinning a message on Discord.  Open to hearing other ideas.

Issue moved to QA.

**Comment by jessicazartler** [comment]
Sounds great, thank you both!

**Comment by tamarandom** [comment]
🙌🏼 @iviangita Looks great!

**Comment by markoprljic** [comment]
Decided! We're using the tweeter planning sheet from @iviangita https://docs.google.com/spreadsheets/d/1TEag2jkNqgpFX9oqsqHZ_cQc6UboggIb6Rxctly15fU/edit?usp=sharing

There's a tab called SUBMIT YOUR CONTENT where anyone can submit content they want to be published on twitter.
