### ISSUE TITLE
Create sub brands for Omega and Stewards WG's

### ISSUE THREAD

**Issue by markoprljic** [TECommons/coordination#462]
## 📋 Anything to add?

Same as for other WG's, banners and geometry symbols that represent those, create for missing WG's.

**Comment by markoprljic** [comment]
Added Omega and Stewards. Updated Branding github repo with new logos. Updated Google Slides template with preview of all WG banners. 
@jessicazartler Please update the slides for new WG's. Thanks.

![Image 2021-02-24 at 6.47.42 am.jpg](https://images.zenhubusercontent.com/5cc090818b624e26c3734d75/5f596fed-77fd-45af-a528-8872ae13ba3d)

**Comment by jessicazartler** [comment]
YYYaaaay! Thanks Marko, these look so awesome! <3 Will make those 2 now

**Comment by jessicazartler** [comment]
Oh @markoprljic can you add the two new symbols so I can make them - omega/stewards -- here on the symbols page slide? 
https://docs.google.com/presentation/d/19mxN1g6XDQcYg5sFujRlWbwpqqfb5rQ6gUKDcWEtEWI/edit#slide=id.gc0405232ba_0_137

**Comment by markoprljic** [comment]
Yes they should be in the branding github repo. Sorry for not labeling them properly yet 😕

**Comment by jessicazartler** [comment]
Ohhh okay cool! Found them, thanks so much!
