### ISSUE TITLE
Transparency - Medium article

### ISSUE THREAD

**Issue by iviangita** [TECommons/coordination#463]
## 📋 Anything to add?

Objective: communicate to the outside and to the inside of the organization the short term and long term scope of the Transparency Working Group

Goals: Facilitate equity of access to information, provide easy mutual monitoring strategies and accountability in Decentralized organizations

Questions to answer: Why transparency?

Theoric bases: Ostrom, DAO2DAO relations

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

## 🔗 Work doc - inspirational links

DAO2DAO conceptual framework

https://medium.com/primedao/conceptual-models-for-dao2dao-relations-ac2b2d3cc84d

OSTROM book club notes 

https://docs.google.com/document/d/1WSwg1IMgKDimY6f5EA8XNYgGc-4B56RgyaXshJ0Vquw/edit#

_Ostrom principle #4 Monitoring_
_Monitors, who actively audit CPR conditions and appropriation behavior, are accountable to the appropriators or are the appropriators.

Without monitoring, there can be no credible commitment, without credible commitment, there is no reason to propose new rules._

**Comment by JuankBell** [comment]
Super!!! i want to help with this!! :D

**Comment by iviangita** [comment]
@JuankBell that's great, your help is very much welcome! Here's the [link](https://docs.google.com/document/d/1toVjBhD78RZHxyjOxQGI26eKGkpjDIzQ9ZKZ6xsuWG0/edit#) to my working doc, I'll ping you for more details :)

**Comment by JuankBell** [comment]
Wow Ivy! I hadn't seen this! great work!

**Comment by Zeptimus** [comment]
@JuankBell I loop you here, We only want 1 member assigned following the accountability practice, we talked before, also wanna have a good score on the audit ha-ha :p thanks you so much buddy you are the best! :D

**Comment by JuankBell** [comment]
Made a suggestion to publish the 1st gen graviton list as an appendix of the article :D

**Comment by tamarandom** [comment]
@iviangita @Zeptimus Finished the second round of editing. Please have a look!

**Comment by Zeptimus** [comment]
Thanks Tam!! u're the best :D lets try to get it publish today @iviangita if its not to late for you

**Comment by iviangita** [comment]
Closing! Thanks everyone!!! :D

https://medium.com/token-engineering-commons/transparency-in-daos-999b17b0ff74
