### ISSUE TITLE
Disputable Voting General Discussion Thread

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#465]
Similar to https://forum.tecommons.org/t/dandelion-voting-parameters-general-discussion/107

**Comment by divine-comedian** [comment]
1st draft ready for review - https://docs.google.com/document/d/12QBf_pEkZ85aPjIQ-0uDn_Y9Jd0u3D1FTgNLxisjbus/edit?usp=sharing

@freedumbs00  @GriffGreen

**Comment by divine-comedian** [comment]
final copy posted to - https://forum.tecommons.org/t/disputable-voting-parameters-general-discussion/267

**Comment by freedumbs00** [comment]
Love it @divine-comedian .   Closing this issue
