### ISSUE TITLE
Get in touch with the DAO research Group Marina mentioned and get their document

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#47]
## 📋   Anything to add?

DAOs research group from the University of Utrecht.
The research is part of the SecureSECO project (https://secureseco.org/projects/)

## 🎉   Subtasks

- [ ] Reach out to them, offer to do a call with them to explain the TEC
- [ ] Beg for early access to their document

## 🤼‍♂️   Reviewer

@Santigs

**Comment by Santigs** [comment]
Marina will put us in contact with them.

**Comment by GriffGreen** [comment]
Marina will try to get early access to the doc!

**Comment by Block007** [comment]
This is Marina :) will do

**Comment by Block007** [comment]
This is the doc: https://docs.google.com/spreadsheets/d/1ZcU-fyvn29knNyxWKK4Xxyi5g0mjjERHaqZr-y0ZEWo/edit#gid=1075344720

**Comment by Santigs** [comment]
We had our first call today, me and Giulio from TEC side and Siamak Farshidi and Elena Baninemeh from https://secureseco.org/
We need another meeting together with TEC so they can better understand our DAO project and the features it will include.
They shared the info of all the DAO's they have already included in the study
https://docs.google.com/spreadsheets/d/1ZcU-fyvn29knNyxWKK4Xxyi5g0mjjERHaqZr-y0ZEWo/edit#gid=1564198724

**Comment by Block007** [comment]
Thank you Santi,

I have shared this file in the GitHub.

Best,
Marina



V V sre., 25. nov. 2020 ob 15:32 je oseba Santi <notifications@github.com>
napisala:

**Comment by tamarandom** [comment]
@GriffGreen Anything left to do on this one?

**Comment by Santigs** [comment]
We had a meeting with them but they needed some tech feedback from our side,
Giulio was leading that.
He suggested meeting after Christmas as Sem was too busy with the test launch.
We can meet sometime this Q1 but we can close the issue from the legal perspective.
