### ISSUE TITLE
Confirm that the Minimum Quorum Forum Post works for Disputable voting

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#470]

**Comment by divine-comedian** [comment]
Changed description in [Disputable Voting Parameters](https://forum.tecommons.org/t/disputable-voting-parameters-general-discussion/267/6) to reflect differences between Disputable Voting and Dandelion Voting in relation to Minimum Quorum

**Comment by freedumbs00** [comment]
Great job Mitch.  Closing this issue.
