### ISSUE TITLE
Review Each of the Previous Parameters Posts and confirm they are still applicable

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#479]
## 📋 Anything to add?

The Vesting Cliff and Vesting Period pieces have been moved to the Augmented Bonding Curve.... are there other pieces that have changed since the original posts were written?

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by freedumbs00** [comment]
We got everything.  Closing issue
