### ISSUE TITLE
Create a video showing people how to propose Params

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#480]
@marthendalnunes @freedumbs00 Lets make it super easy to propose params!

I hope to show them how to star from scratch, and how to start with someone else's params.

**Comment by markoprljic** [comment]
@freedumbs00 You meant to record a video walkthrough on using the Hatch Dashboard? If so, you think you can do this in the coming sprint?

**Comment by freedumbs00** [comment]
Yes

**Comment by markoprljic** [comment]
@freedumbs00 @GriffGreen Is Vitor going to record the walkthrough? What is the final decision about this?

**Comment by freedumbs00** [comment]
I made the video.  Zep it adding to the TEC Youtube
