### ISSUE TITLE
Twitter content: Invite hatchers to Hatcher Outreach Community Call

### ISSUE THREAD

**Issue by iviangita** [TECommons/coordination#482]
## 📋 Anything to add?

Context from @eduardovegap:

We will have our first hatch outreach community call, to welcome people who is interested on being hatchers. Yes, It's an open call, where we will welcome everyone intersted on being a hatcher for the TEC, and explain how it works, what it's about and explaining the process to become one. 

## ⏰ Urgency/Due Date/Blockers?

Before March 4

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@eduardovegap @jessicazartler @markoprljic

**Comment by iviangita** [comment]
Hi @jessicazartler @markoprljic @eduardovegap, hope you can review the content I drafted before I publish :)

_🐣 We're pipping! 

Would you like to be our hatcher? Learn how to become one and find out what's in it for you!

Join our first Hatcher Outreach Community Call tomorrow at 1pm CET: https://discord.gg/mEv63xeWGn  

Look forward to welcoming you! 🐥

#TokenEngineering_

I also created 2 options for the graphic - let me know which you prefer:

**Version 1**
![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/ec30ba09-cbfc-43eb-95c5-1978e95501ab)

**Version 2**
![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/1e66f90a-ac6d-4d45-8563-e1ecc51d6852)

**Comment by markoprljic** [comment]
Thanks @iviangita looking good!

I think Version 1 if the banner is more clear and action driven. Let's go with that.

**Comment by jessicazartler** [comment]
Agree with Tamara on the first graphic and one more suggestion:

"Would you like to be our hatcher? Learn how to become one and find out what's in it for you!"

Many people don't know what a hatcher is.. so maybe we could say "Would you like to become a founding member of the TEC? Learn more about the benefits and the mission that drives us"

Or something like that - thanks Ivy! Fantastic work!

**Comment by eduardovegap** [comment]
Agree with their feedback and @jessicazartler change to the tone of the approach.

**Comment by iviangita** [comment]
@markoprljic @jessicazartler @eduardovegap thanks for the feedback! Here's the final copy for release:

🥚 We're pipping! 

Would you like to become a Hatcher, that is, a founding member of the TEC? Learn more about the benefits and the mission that drives us! 🐣 

Join our first Hatcher Outreach Community Call tomorrow at 1pm CET: https://discord.gg/mEv63xeWGn  

#TokenEngineering 

![Hatcher Outreach - Mar 4.jpg](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/31b7d760-6f2d-4b68-b736-fbdd443ff161)

CLOSING this issue now! :D
