### ISSUE TITLE
Disable / delete the "old" new Discord server 

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#483]
## 📋 Anything to add?

The "new" new Discord server is going live. 
This one : https://discord.gg/hyQQrAdad4

The "old" new Discord server link is still out in the wild. 
We need to disable or delete that server, please.

@krisjpi is there anyone other than you that can do this? ;)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by Vyvy-vi** [comment]
I think only kris can do that since they own that server.

**Comment by krisjpi** [comment]
Sorry for the delay, had to get 2FA involved, but it is now deleted! The only TEC server that exists now is the legitimate server! Join us over there - https://discord.gg/vun8mEQWew

**Comment by tamarandom** [comment]
🙌🏼
