### ISSUE TITLE
Hatch Phase TL;DR

### ISSUE THREAD

**Issue by divine-comedian** [TECommons/coordination#486]
This is document is a basic summary of the hatch process that will be shown to potential hatchers 

https://docs.google.com/document/d/1Ji2vV5c_PCXt2q0G-1wTddyOaUp5ESKWht2UKcoE7S0/edit?usp=sharing

**Comment by divine-comedian** [comment]
final draft ready for review @GriffGreen  @freedumbs00

**Comment by eduardovegap** [comment]
Thank you Mitch, I gave some notes. Shall we make an illustration for the vault part? I think there was one, mainly because I feel it's the only confusing part to understand. And I would divided in steps to make it easier.

**Comment by divine-comedian** [comment]
@eduardovegap  I hear ya!  If someone is able to make an illustration sure. All the flow charts I've seen thus far make it feel more complicated, I divided it into 3 steps roughly and named them

**Comment by freedumbs00** [comment]
This is a great idea.

**Comment by tamarandom** [comment]
Closing! Thanks @divine-comedian looks great!
