### ISSUE TITLE
Transparency WG Audit

### ISSUE THREAD

**Issue by iviangita** [TECommons/coordination#489]
## 📋 Anything to add?

@Zeptimus @iviangita Transparency WG will do the first transparency audit and go through the Advice Process to see how it works in reality

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by Zeptimus** [comment]
Update: https://forum.tecommons.org/t/transparency-wg-audit/290
