### ISSUE TITLE
Tracking and process for DAO2DAO onboarding

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#49]
## 📋   Anything to add?

This is a long term project but it can be broken into smaller steps

## 🎉   Subtasks

- [ ] Find a champion
- [ ] Scope out the plan below
 

## 🤼‍♂️   Reviewer

@jessicazartler @cranders1 @liviade1

**Comment by jessicazartler** [comment]
DAO2DAO onboarding from Seeds 
https://docs.google.com/forms/d/e/1FAIpQLSd35uWAOA-00B6QvucIhj_ft3dTSIaHJyjgLLisXNbgMJeMUw/viewform?_hsmi=98908737&_hsenc=p2ANqtz--nzUVTZkZeMHkm7_e4PXlKbs8KrymOdXkDEqoaJh4NI4cFmZ7h77SBSFpLmtD1odtuU6juOgtJ7GyAhoAuW41HwD65Gg

**Comment by jessicazartler** [comment]
Zargham, Shermin and others are working on the wider scope for DAO2DAO... the only onboarding we have is to have projects submit proposals for funding which we are tracking and already finished the process for here:
https://docs.google.com/spreadsheets/d/1RJK8gPqUoRfehX9e60sTCMAM_R1rI2CuiV1r-i3wAXQ/edit#gid=875503092

The rest of the issues are related to CS and are also represented there.. so I am going to close this issue for now.
