### ISSUE TITLE
SEO - Set up Google analytics / Social media analytics

### ISSUE THREAD

**Issue by markoprljic** [TECommons/coordination#492]
## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by markoprljic** [comment]
@rosamoc I would need a bit more context and steps needed to complete this in order to assign more people (if needed).
When you find the time please let me know what the process looks like and what is required for each step in order to successfully set up analytics for channels and platforms. I'll update the issue description accordingly.

**Comment by rosamoc** [comment]
@markoprljic Yes, for this it is needed:
- Open a google account and get the google analytics proprietary code to insert it in the plugin of the site
- I don't know if it would be interesting to set up a standard report with google data studio. You can link it with several external sources (hubspot, analytics, social media...) and thus have more accurate data.

**Comment by markoprljic** [comment]
@Zeptimus You can access gmail? Do we have Google Analytics installed? We would need to do that for the website. Would you be up to setting this up so that Rosa can add it to our website?

**Comment by Zeptimus** [comment]
I'll need to sync with jess for the 2FA since i restarted my computer, never used google analytics before but i can try give me the weekend and ill give an update :)

**Comment by markoprljic** [comment]
> I'll need to sync with jess for the 2FA since i restarted my computer, never used google analytics before but i can try give me the weekend and ill give an update :)

Re: setting up GA, first we want to get the code to implement on the site. When you log in to Google and go to Analytics you'll be able to create new site and generate GA code.  https://support.google.com/analytics/answer/1008015?hl=en

Setting up funnels and all that stuff can be done at later stage, and maybe we do want someone with more experience to take on this? @rosamoc Would you be up to take ownership of this?
We could add a user to GA with specific permissions @Zeptimus https://support.google.com/analytics/answer/1009702?hl=en

**Comment by rosamoc** [comment]
@markoprljic  Yes I can do it! To start I would need the GA code, if you give me access to the google analytics account (with my email) I configure everything myself, both the web and all other tracking tools.

**Comment by markoprljic** [comment]
You made my day! Thanks @rosamoc :)
Best would be to sync with @Zeptimus so he can add you to Google account with your email address.

@Zeptimus When you can please, can you DM Rosa (or the other way around) to add her as a user to our GA?

**Comment by Zeptimus** [comment]
awesome! ill sync with her

**Comment by rosamoc** [comment]
@markoprljic @Zeptimus Code has been added
