### ISSUE TITLE
help onboard ygg as a hatcher 

### ISSUE THREAD

**Issue by liviade1** [TECommons/coordination#507]
## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by freedumbs00** [comment]
@liviade1   Juan and I onboarded YGG.  He recorded it and posted on our youtube channel for a case use.  Juan also took fantastic notes and submitted them in the google doc.   https://docs.google.com/document/d/1Vja9gRNE06RTOTjKWws4uFc06jWlpYFiK3dowWozBbI/edit#

https://www.youtube.com/watch?v=Cn0KnqzOB7M.   This the part A

https://youtu.be/fyGTQdO1DQc.   Part B
