### ISSUE TITLE
Discord : Get the Groove bot working on all the Voice Channels 

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#513]
## 📋 Anything to add?

Please!? ;) 

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by Vyvy-vi** [comment]
done-!
However, there is a _small_ catch.
Groovy can play music only in 1 channel at a time(*unless we pay premium to use it's secondary servers, ref: <https://groovy.bot/premium>)

We could however get secondary music bots, if needed :)
