### ISSUE TITLE
Distribute Mitch's new content piece 

### ISSUE THREAD

**Issue by markoprljic** [TECommons/coordination#516]
## 📋 Anything to add?

https://forum.tecommons.org/t/the-hatch-tl-dr/272

Get into the praise quant blog.
Sharing in various channels in our ecosystem, Jess has a distribution list. 

## 🤼‍ Reviewer

@markoprljic

**Comment by markoprljic** [comment]
@iviangita Is this something for you?

@jessicazartler Can you share your approach, distribution list, strategy etc?

**Comment by jessicazartler** [comment]
The piece must be appropriate for the channel and the message should not be spammy, something tailored to the group that is why people in that group would care. Would also be great to have different people taking on different channels to post so not all comes from one person.

Here are the main channels - this can be built out -  but again, depends on the piece. We could also have sharing templates for people to do one on one sharing for friends/colleagues for pieces that are specifically of interest to them. Ideally need a contributor to lead these efforts, get more organized/process/templates for this - a content sharing network with our partner projects would be wonderful.

Here are the main channels I usually distribute in:
- [ ]  TEC news blog
- [ ] TEC general discord
- [ ]  TEC Twitter
- [ ] ask CS to RT
- [ ] Commons Stack Telegram
- [ ]  cadCAD forum
- [ ]  cadCAD telegram channel
- [ ]  Partner channels: 1Hive, MetaGame, Whaler DAO
- [ ]  CS newlsetter
- [ ] TEC newsletter (could be developed)

**Comment by tamarandom** [comment]
@natenatesoo @jessicazartler -  

By TEC News blog, does that mean Medium? (https://tecommons.medium.com). In theory we can post to medium without it having to also be part of the bi-weekly blog post. That's why I ask. 

Plus, more! 
[ ] TEC Forum 
[ ] TEC Gitbook
