### ISSUE TITLE
tecommons.org buggy rendering on iphone 

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#522]
## 📋 Anything to add?

Screenshot : 

![photo_2021-03-12_10-59-59.jpg](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/ec7dfbc7-9c11-4d97-a3b7-6538a04ab834)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by tamarandom** [comment]
hey @markoprljic - This happens on all 3 browsers on my iPhone :  Safari, FF and Tor.

**Comment by markoprljic** [comment]
Assigning this to @kristoferlund Hopefully he can fix this. Kristofer, what do you think?

**Comment by kristoferlund** [comment]
Now better. Still not 100% though, what do you think? Wordpress + the graphical editor (Elementor) makes it rather difficult to fine tune the looks for different screen sizes. 

![screenshot_20210319-230657](https://user-images.githubusercontent.com/9698363/111846971-2f39e880-8908-11eb-957a-066ae252278e.png)

**Comment by markoprljic** [comment]
@tamarandom Can you do another test and let us know if it's better?

**Comment by tamarandom** [comment]
Thanks @markoprljic - I did see @kristoferlund's update. ;) But my response is not a simple yes/no answer so I did not reply straight away. Let me share it now. This surfaces a larger question and here's my POV on it:

It all comes down to how we much we value a web2 presence for the TEC and, from there, to determine how much effort we want to invest in that direction. If the answer to that question is none, then there is nothing left to do. We can close this issue and forget about it. If the answer is medium to high, then there is a bigger effort that we should undertake because we should be designing for the mobile experience first and not the other way around. 

When I was at BBDO, and this was 6 years ago, we were already in a mobile-first mindset. At the time mobile traffic was in the 30% range but it was obvious that mobile traffic would overtake desktop. It did in 2016. Here's a picture of what that looks like. (source : https://gs.statcounter.com/platform-market-share/desktop-mobile-tablet/worldwide/#yearly-2010-2021) ![StatCounter-comparison-ww-yearly-2010-2021.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/93836c1d-8904-4b01-8f9d-d17f4081c824)

I like Chrome's built-in device emulation tool. They have a lot of options out-of-the-box and I can see what it looks like on devices I don't have. ![Screen Shot 2021-03-20 at 10.17.53 AM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/108b2cfc-3087-4aab-bfc9-7ced8a6852e8) 

For mobile users, over 50% of web traffic, tecommons.org is not a good experience. Here's what iPhone X users see: 

![Screen Shot 2021-03-20 at 10.20.42 AM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/ee1329ef-849b-4233-abfc-69e51acb28bb)![Screen Shot 2021-03-20 at 10.20.50 AM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/9dfbd159-e97d-42d7-a0f6-fa4b91f70ff3)![Screen Shot 2021-03-20 at 10.20.59 AM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/973f7829-2a97-4572-8ff6-4bde30d1c3c1)![Screen Shot 2021-03-20 at 10.21.16 AM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/fa62bfc6-be51-44f9-9c2e-7108fc7b52d4)![Screen Shot 2021-03-20 at 10.21.51 AM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/7c7b7a3f-6bd0-40d5-940e-051bf814a0d7)![Screen Shot 2021-03-20 at 10.21.58 AM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/8e71c026-52e8-4a6b-b095-acc07cc942d4)![Screen Shot 2021-03-20 at 10.22.11 AM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/7e43b260-f670-4667-a61b-27a7f2af4f86) 

My personal opinion is that there is high value for the TEC to maintain a low-effort, high-quality web2 presence. It should be a great experience on the most widely used mobile devices (https://gs.statcounter.com/browser-market-share/mobile/worldwide#yearly-2010-2021) and good elsewhere. Despite our building web3, the majority of the world is still in web2 and the TEC website has intrinsic value as a primary communication channel that represents us to them.

**Comment by markoprljic** [comment]
Thanks for the extensive review and feedback @tamarandom I completely agree with you on all points and I'm very much aware of the issues. Being limited with resources at this stage I was satisfied with what we currently have, even if not perfect. 
Next step would be fixing mobile views (possibly within the WP Elementor settings), and after that IF we can (and I pray we do) build our own front-end that we can fully control and hook it up to WP or other CMS of choice. 
In addition to above I'm also seeing website being updated with additional pages and content (Working groups, Forum, Blog, Medium posts maybe, other featured content etc.)

That being said we will gradually upgrade and fix issues along the way. 

It would be great if we can have @kristoferlund or someone dedicated to front-end / WP and myself for design. Eventually if needed also someone specifically taking on backend issues. 

If you come across a contributor for this please send them my way :)

**Comment by tamarandom** [comment]
You got it, @markoprljic. Your designs are rockstar⚡⚡⚡ , the mobile render constraints of WP do not allow them their full justice. 

Closing!

**Comment by kristoferlund** [comment]
Great feedback @tamarandom! Wordpress definitely has its constraints when it comes to mobile first responsiveness. Perhaps the Wordpress website could be fixed to look good on mobile, I doubt it would be worth the effort though. Since the site currently is just a single page / landing page, building a mobile first page from the ground up is _not_ a major effort. 

Is now the right time to do it? I don't know. It depends on what else is in the pipeline before the hatch. Let's discuss and prioritise in the coming week.
