### ISSUE TITLE
Hubspot integration in Wordpress not working

### ISSUE THREAD

**Issue by markoprljic** [TECommons/coordination#526]
## 📋 Anything to add?

Subscribing to emails on the website is not sending records to Hubspot account. @knobsdao looked it up on HubSpot, yet the info isn't there. Are the emails being recorded elsewhere? Ideally, we want them to go straight to Hbubspot but a spreadsheet is good enough for Dan to make the data sync.

**Comment by kristoferlund** [comment]
👍 Great, I'll have a look.

**Comment by kristoferlund** [comment]
I'm pretty sure I solved it, have a look at the topmost row below. Someone with access to hubspot please verify. @knobsdao?

![image](https://user-images.githubusercontent.com/9698363/111828144-225acc00-88eb-11eb-8b2a-f392a2e2ba33.png)

**Comment by knobsdao** [comment]
Yeah! Solved! Just found your entry and tried with my own email. All good.
