### ISSUE TITLE
Migrate from Wordpress to Netlify

### ISSUE THREAD

**Issue by markoprljic** [TECommons/coordination#553]
## 📋 Anything to add?
Migrate current website from Wordpress to Netlify and make it fully responsive!

## 🤼‍ Reviewer

@markoprljic

**Comment by kristoferlund** [comment]
Great! The development build is available here: 
https://naughty-lalande-8b2365.netlify.app/

**Comment by kristoferlund** [comment]
Now there is a repo for the "new" web. A few small things to polish up but mostly done! 

https://github.com/TECommons/tec-web

**Comment by markoprljic** [comment]
https://tec-web.netlify.app/
