### ISSUE TITLE
TWEET: cadCAD bootcamp study group

### ISSUE THREAD

**Issue by iviangita** [TECommons/coordination#560]
## 📋 Anything to add?

From @bvanderlugt: 

Hi folks  I am working with ygganderson to kick off a beginner/foundational cadCAD study group for the TEC labs series starting April 2nd. The plan is to go through the cadCAD bootcamp material and have at least one guest demo/QA from the cadCAD academy instructors (maybe hold a session on an advanced topic aka "cadCAD hacks"). I did reach out to @iviangita for help (thanks!! ) but would also like to share out with the wider comms group. 

The plan is to kick off April 2nd and it would be awesome to have a TEC tweet at the end of this week so we can build some  hype  I have conflicting meetings during the comms call but I'll try to catch the last few minutes.

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@markoprljic

**Comment by iviangita** [comment]
Hey @bvanderlugt, I revised the wording you sent me via Discord because Twitter has limited characters. I also created a graphic for it - we can add a photo of you or any cool image that will represent the topic :) Please check the draft below and feel free to edit or suggest any changes! 🙂

cc: @jessicazartler for other content edits :D

**Draft tweet:**

Looking for a group to begin your token engineering journey with? We got you!

Join our self-paced cadCAD Bootcamp academic series every Friday, plus a Q&A session w/ course instructors! 📚🎖️

Starts on Apr 2 at 8 PST / 17 CET 🚀

https://discord.gg/YZA2TrFJ7u 

Hosted by @BlairVee 👨‍🏫

![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/b992da1e-f602-403e-82bb-75e6834472e6)

**Comment by jessicazartler** [comment]
This is awesome!!!!!! Thank you Ivy & Blair - just changed the slide title a bit - otherwise, looking great and can't wait to join!

@bvanderlugt is this to go over Jonathan's course? If yes, for an image, I would screenshot something cool looking from the course would be great to have an image on here as now we have so many events - it would stand out more :D cheers!

**Comment by iviangita** [comment]
Thanks @jessicazartler! I revised the tweet and the graphic and added them in this [document ](https://docs.google.com/document/d/1EbkDoObU8tJrRwjrqYxyJ8nrD635Es_i272d2fVWFpk/edit?usp=sharing)- feel free to suggest edits. If these are okay, I'll proceed and publish them once @bvanderlugt confirms the schedule :D

**Comment by jessicazartler** [comment]
It's perfect - so cute the image! Thank you so much, looks AWESOME!

**Comment by jessicazartler** [comment]
@iviangita @bvanderlugt I also added it to the TE, CS, cadCAD public calendars :D

**Comment by iviangita** [comment]
@jessicazartler thank you! will add the cal link to the repeating tweet :)

Closing this one as the announcement was already out: https://twitter.com/tecmns/status/1376605576596103174?s=20

**Comment by jessicazartler** [comment]
Awesome thank you! :D Nice!!!
