### ISSUE TITLE
Youtube page 

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#565]
## 📋 Anything to add?

Is it possible to order the videos so that the NEWEST one is on the top of the list? Right now the first video on the playlist are the oldest ones. It would be great is the newest one is the first to play when someone goes to the playlist. 

![Screen Shot 2021-03-26 at 3.37.20 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/b2d3a830-6463-4c98-b69a-9389b256c69a)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by Zeptimus** [comment]
Yeah the logic behaind it was first things firts but i agree it is not a tv show we dont have to start from the oldest one :D, ill fix it during the day :)

**Comment by Zeptimus** [comment]
Done!
