### ISSUE TITLE
Hand-off the Twitter 2-FA

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#569]
## 📋 Anything to add?

Help! We need easier access to the twitter account, can we make a sesh to pass off the 2-fa?

@markoprljic can you help make this happen? I don't know who wants to have the 2-fa... but it should be someone in the Stewards group.

## ⏰ Urgency/Due Date/Blockers?

this week

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by Zeptimus** [comment]
I can step in here if u guys want, my telegram dms arent scary for now :p but the important thing when sharing phone number, its people engage with keybase.

**Comment by markoprljic** [comment]
@Zeptimus Can I reasign this one to you then?

**Comment by Zeptimus** [comment]
Yes, if i have any problem ill let you know on comms meeting today :)

**Comment by Zeptimus** [comment]
ok we can close this issue i deleted the  old phone number and added google authentificator i have the code it would cool if more people held it in case my phone get lost or something. Ill update this information on the keybase pinned missage

**Comment by markoprljic** [comment]
Awesome!
