### ISSUE TITLE
Principle 5 - start mutual accountability methods 

### ISSUE THREAD

**Issue by liviade1** [TECommons/coordination#59]
## 🎉   Subtasks

- [x] host a session to brainstorm mutual accountability methods 
- [ ] document most interesting methods from the call
- 

## 🤼‍♂️   Reviewer

@

**Comment by liviade1** [comment]
@Zeptimus @JuankBell can we add the progress here?

**Comment by tamarandom** [comment]
Update : collaboration between Soft Gov & Transparency to write proposal

**Comment by tamarandom** [comment]
looping in @Zeptimus

**Comment by Zeptimus** [comment]
https://docs.google.com/document/d/1A-tJgOm8mUF6Fqq2MF6ukZyhChVmFF7uqKQ2feD-azs/edit

**Comment by Zeptimus** [comment]
Close: https://forum.tecommons.org/t/mutual-accountability-methods/286
