### ISSUE TITLE
Make a stock and flow diagram for the flows for the Hatch

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#61]
## 📋   Anything to add?

There might have been a starter already

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by Santigs** [comment]
This is the 1hive forum post I was referring to
https://forum.1hive.org/t/together-we-thrive/1278

**Comment by jessicazartler** [comment]
https://github.com/TECommons/coordination/issues/64
I had already made one and would have been more work to delete that since it was filled out - ah thanks! Next time we will say who is making issue thanks Griffffffffffffffff
