### ISSUE TITLE
Investigate Nexus Mututal

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#65]
## 📋   Anything to add?

They have an insurance company that was set up to connect to a bonding curve... they have to follow some serious rules came out of convo in #35 

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by joshuavial** [comment]
I've been diving in to Nexus Mutual recently - here is a write up of what I've learned so far. 

## Summary
Nexus Mutual is an insurance DAO incorporated as a formal mutual in the UK. It has around 5k members and offers insurance-like cover for smart contract failure, with plans to offer cover for wallets and standard risks (e.g. earthquake) in the future. 

## Legal Structure
Nexus Mutual is established as a company limited by guarantee in the UK - the Financial Conduct Authority have given them the right to use mutual in their name.

Members are part-owners of the mutual and the NXM token is used to represent membership rights. Here is a list of the [company filing history](https://find-and-update.company-information.service.gov.uk/company/10917763/filing-history) including the articles of association.

## Membership
Each member goes through KYC and pays a 0.02 ETH membership fee. Membership conveys the following entitlements
  * Purchase cover with ETH or NXM
  * Stake NXM to vote on claims - voting with consensus earns NXM, voting against locks it, voting fraudulently burns it
  * Vote on governance - NXM is the voting weight, participating in votes earns NXM, tokens are locked for a period after voting
  * Assess risk by staking tokens against specific contracts and earning NXM when cover is purchased against that contract. If a successful claim is made against that contract in 250 days some stake is burned

## Token design
Only Nexus Mutual Members can purchase, hold or use NXM - tokens can be purchased or redeemed at any time at a variable price computed algorithmically. 
The token is intended to align long term interests of mutual members and align the price with the financial performance of the mutual.
The [token model page](https://nexusmutual.io/token-model.html) covers the details, but the key variables driving the price are 
- Capital pooled in the smart contract
- Minimum Capital Requirements (MCR) for issued cover
- MCR% = Capital Pool / MCR - this is the key number which drives the token price - MCR% goes up/down, token price goes up/down

Price = A + (MCR / C) * MCR%^4

Price and MCR are denominated in ETH, A and C are constants set at token launch time to set initial value of token.

Members can redeem their NXM for ETH at a price 2.5% below the calculated buy price. Redemptions are contingent on MCR% > 100  and there being enough Ether in the capital pool. There is also a cap on the amount of NXM that can be redeemed per transaction.

## Cover and Claims
The [smart contract cover](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiO_JS3m_nsAhWAxzgGHdDNB4gQFjABegQIAhAC&url=https%3A%2F%2Fnexusmutual.io%2Fpages%2FSmartContactCoverWordingv1.0.pdf&usg=AOvVaw2sDKEkWOp8hBaBSPfIdUCs) is a 3 page, high level document describing the smart contract cover. Claims are paid on a discretionary basis and the mutual members acting as claims assessors have the final say on whether a claim should be paid or not. 

Member stake NXM when assessing a claim - if they agree with the consensus of other assessors they will receive a reward in NXM for assessing a claim. If they disagree their stake will be locked, if they are acting fruadulently there is the potential for their stake to be burned. As a discretionary mutual their is no legal obligation to play claims and the system relies on members acting honestly when assessing claims. While it would be in the short term interest for members to deny claims and preserve capital this would quickly lead to loss of future customers purchasing cover and the DAO relies on long term incentives of a healthy mutual and NXM token price keeping the behaviour of assessors honest.

## Governance
The DAO uses [GovBlocks](https://govblocks.io/) to make decisions together
* Members can be incentivised to vote on governance, a proposal will indicate the total rewards pool for participating in the decision
* Proposals can be limited to specific groups - e.g. proposal #111 to adjust voting period from 7 to 3 days was open only to the advisory board
* Members can delegate their votes to others and anyone can update their account to indicate they are willing to accept delegations
* As of review date there were 36 formally defined proposal categories - each category specifies
  - whether it is a special resolution requiring 75% majority
  - which roles have the right to propose 
  - which roles have the right to vote 
  - the minimum requirements for quorum (%), number of tokens staked before creation, token rewards to be distributed on acceptance
  - whether the proposal will lead to an automated on chain action (contract and signature of function to be executed)
  - some categories have the ability for the advisory board to decide if quorum of members is not met
    - e.g. 'Extend of Switch off Emergency Pause' requires 15% quorum of members to vote, but the Advisory board can pass the proposal with a 60% majority if quorum is not reached
* There are 3 roles Members (5287), Advisory Board (5), Owner (1)
* There appears to be a healthy culture of discussing proposals in forums - and the [potential protocol changes](https://forum.nexusmutual.io/c/potential-protocol-changes/8) is the most active category in the forum with ~7 topics / month

## Resources
* [Whitepaper](https://nexusmutual.io/assets/docs/nmx_white_paperv2_3.pdf)
* [Public Website](https://nexusmutual.io)
* [Documentation](https://nexusmutual.gitbook.io/docs/)
* [Live data](https://nexustracker.io/)
* [Forums](https://forum.nexusmutual.io/)
* [App](https://app.nexusmutual.io)
* [Article by founder comparing Nexus to prediction markets and derivatives](https://medium.com/@hugh_karp/comparing-insurance-like-solutions-in-defi-a804a6be6d48)

**Comment by GriffGreen** [comment]
Zeptimus will review

**Comment by drllau** [comment]
Legal review of the current [Articles of Association ](https://find-and-update.company-information.service.gov.uk/company/10917763/filing-history/QTg2TlRPR1phZGlxemtjeA/document?format=pdf&download=0) under the laws of UK. The essence is membership contribution in return for **discretionary** cover aka self-insurance

1. Mutual is association of members 
- limited by guarantee so **no** shares
- quorum of 20% for formal meetings (general/special)
- smart contract defined as "protocol .. to digitally facilitate, verify or enforce the negotiation or performance of a contract allowing ... credible transactions without 3rd party
- rules govern member-member interactions
- raise or borrow monies, or guarantee payment for contract 
- can appoint/delegate a **community interest company** to manage aspects of business
- winding up excess contributions donated to charity and illiquid assets (tokens?) distributed according to formula  
- maximum liability is 1 pound (for purposes of winding up) up to 1 year after leaving

2. Board of (executive) Directors (2-5)
- separate? 5 **advisory** board differs from traditional firm supervisory role)
- self elected with power to remove themselves
- no alternate during meetings
2.1 Duties ... good faith towards success of mutual
2.2 Powers
- power to approve membership (incl orgs)
- power to define classes of members with different rights/obligations
- determine meetings (agenda?)

2.3 Conflict of interest
a lot of details ... most likely copied from other mutuals

3. Membership (detailed elsewhere???)
3.1 Application
3.2 Removal

4. Cover
- payment of claims related to liabilities, losses or expenses
- enter into (re)insurance for individual member, subset or mutual as whole

5. Decision
voting = 1+ (#tokens (special) || max(5%. tokens) (normal))
poll (mechanism as specified in general notice)
proxy vote valid if 48hrs interval b4 meeting but can be overridden by appointor
6 month director honeymoon to unilaterally modify contracts for external compliance purposes

This type of arrangement (executive directors) falls into the self-appointed wise-(wo)men ... however may fall afoul of UK's shadow-director laws. However, given the low exit cost (liability of 1 pound) and residual claim (up to 5 years) there's incentive to keep membership up. But quorum of 20% suggests possible scaling livelock at future stage.  Intriguing they have option to delegate to a CIC.
