### ISSUE TITLE
Remove the word Vesting for Locking

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#67]
## 📋   Anything to add?

We are really doing Locking... not vesting

## 🎉   Subtasks

- [ ] Decide the level of changes
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by drllau** [comment]
They are actually 2 separate legal concepts ... vesting is where ownership passes to recipient (though can be reversed if provided under bad leaver provisions) whereas lock-up is ownership is already assumed and the undertaking is not to sell/dispose within a certain time period

**Comment by iviangita** [comment]
Copied and moved to Gardens Swarm Workspace [issue 9](https://app.zenhub.com/workspaces/garden-swarm-workspace-5fe322aef3aab0001be1d518/issues/tecommons/tec-ui/9)
