### ISSUE TITLE
Make a list of 20+ TE projects that might want to submit proposals to the TEC

### ISSUE THREAD

**Issue by liviade1** [TECommons/coordination#68]
## 🎉   Subtasks

- [x]  Find Champion
- [x] Jess sync with CS people to rack brains for projects/contacts 
- [x] Eduardo filter & build out the list that is already there 

## 🤼‍♂️   Reviewer

@eduardovegap @jessicazartler 

## 🔗   Work doc - inspirational links
https://docs.google.com/spreadsheets/d/1qI76CCykCrrctKWe7Oydzs31fYgbgR5JhJUUVZ8j7Yo/edit?usp=sharing

**Comment by jessicazartler** [comment]
We are using the Curate doc to log organizations/projects we are approaching to submit proposals for the TEC
https://docs.google.com/spreadsheets/d/1RJK8gPqUoRfehX9e60sTCMAM_R1rI2CuiV1r-i3wAXQ/edit#gid=0

I would say this is done! :D
