### ISSUE TITLE
Governing the Commons Bookclub

### ISSUE THREAD

**Issue by liviade1** [TECommons/coordination#73]
## 🎉 Subtasks

- [x] session 1
- [ ] session 2 
- [ ] session 3 
- [ ] session 4
- [ ] session 5
- [ ] session 6

## 🤼‍ Reviewer

@

**Comment by drllau** [comment]
Perhaps the bookclub could be part of Commonstacks social forums rather than token-engineering (which is more technical/cryptoeconomics)? All seeders are members of common stack after all
