### ISSUE TITLE
Collect feedback and iterate on the Forum Proposal Structure 

### ISSUE THREAD

**Issue by cranders1** [TECommons/coordination#79]
## 📋 Anything to add?

See current Forum Proposal Structure, collaborate, iterate
https://forum.tecommons.org/t/test-2-conviction-voting-commons-proposal-guide-example/40

## ⏰ Urgency/Due Date/Blockers?

**URGENCY**: Medium
**DUE DATE**: Ongoing
**BLOCKERS**: None

## ❓ Why is it important?

Receive community feedback on future proposal mechanisms both in the TEC Forum or alternative

## 🎉 Subtasks

- [x] Find Champion 🙏 
- [x] Interact on the TEC forum in the Proposals Channel and elsewhere to generate discussion and collect feedback 
- [x] Make a Forum Proposal Structure Proposal
- [x] Implement

## 🤼‍ Reviewer

@jessicazartler 

## 🔗 Work doc - inspirational links
[Forum Proposal Template](https://forum.tecommons.org/t/test-2-conviction-voting-commons-proposal-guide-example/40)

[TEC Onboarding and Resources Guide](https://docs.google.com/document/d/1UDnf26QQqqc77mnhn80MLCVzJU6IdvouT-OXPrIVXCg/edit?usp=sharing)
[TEC Forum Proposal Template ](https://forum.tecommons.org/t/test-2-conviction-voting-signaling-proposal/47)

**Comment by drllau** [comment]
The Legal Working group identified that there is serious risk of proposals being funded but not delivered on time or with expected quality. I suggest considering a 3 phase approach

1. Simple outline MoU ... (link to token white paper) with 
- idea, 
- outcome, 
- impact on TEC, 
- budget (min,desired,max)

2. TEC Shepherds look at it to refine
- milestones / testable outcome
- deliverables
- schedule (if any)
- Stewards to approve a Letter of Intent

3. Goes out for TEC conviction voting based on mutually agreed funding range
   If reach minimum, then an agreement for the funding gets executed

**Comment by jessicazartler** [comment]
Template up on forum with edits :D
