### ISSUE TITLE
Publish requirements for becoming a TEC Hatcher

### ISSUE THREAD

**Issue by cranders1** [TECommons/coordination#81]
## 📋 Anything to add?

Develop framework and template for TEC Hatch readiness, intention, and onboarding procedure by building off current documentation and refining as necessary.

## ⏰ Urgency/Due Date/Blockers?

**URGENCY**: High
**DUE DATE**: Dec 3 or ASAP
**BLOCKERS**: Finalized reqs
: Legal?

## ❓ Why is it important?

Establishing consistent and meaningful TEC Hatcher onboarding requirements

## 🎉 Subtasks

- [ ] Sync with other WG stewards to incorporate inputs
- [ ] Develop standardized TEC Builder requirements template

## 🤼‍ Reviewer

@

## 🔗 Work doc - inspirational links
[TEC Onboarding and Resources Guide](https://docs.google.com/document/d/1UDnf26QQqqc77mnhn80MLCVzJU6IdvouT-OXPrIVXCg/edit?usp=sharing)

**Comment by drllau** [comment]
Feed results into #28 and LegalWorking Group to ensure part of any disclosure doc

**Comment by drllau** [comment]
Get sign-off that they are participating in beta-software and aware of the risks involved. LegalWorking group to formulate disclaimers.

**Comment by tamarandom** [comment]
Let's look at this in our onboarding WG backlog grooming session.

**Comment by Santigs** [comment]
Terms and conditions have been stablished.
App almost finished to onboard hatchers

**Comment by GriffGreen** [comment]
https://docs.google.com/document/d/1jJAlLi6zE4lktvnzyloscNyyDc9UHPy6BuhI7yT-Qv0/edit?usp=sharing

**Comment by jessicazartler** [comment]
What are the things needed still before we can write this? Is it just the completion of the vote/CSTK token dapp or is there anything else? @GriffGreen @Santigs

**Comment by tamarandom** [comment]
Feedback: this can be written now but wait to publish until the dApp is live and there is a link to share along with the communication.

**Comment by tamarandom** [comment]
Closing, the draft (meat and potatoes) passed to Comms (to add side dishes).
