### ISSUE TITLE
TEC Stories 

### ISSUE THREAD

**Issue by jessicazartler** [TECommons/coordination#9]
## 🎉   Subtasks

Write The Why stories about TEC.
References to earlier works below. 

## 🤼‍♂️   Reviewer

@GriffGreen @jessicazartler @manualzuru 

## 🔗   Work doc - inspirational links
Andrew made this doc - thank you Shinichi! You da best!!
https://docs.google.com/document/d/13usgfCW35wJf4bi7Mm-HOsKtTbH

https://miro.com/app/board/o9J_kjDw5AE=/
Password: TokenEngineering

**Comment by jessicazartler** [comment]
This is more of an epic @tamarandom -- I need to identify smaller things to break this into...

**Comment by tamarandom** [comment]
This is a dupe of another issue or epic? Maybe we close, @jessicazartler ?

**Comment by jessicazartler** [comment]
Maybe close it? It was about scoping content pieces -- I think we will be good for the "narrative" once I publish this why piece and edit the web content.. then we will be more in the phase of hatch content - which is an epic
https://miro.com/app/board/o9J_krl8Cv0=/
