### ISSUE TITLE
Summary of Stakeholder Research

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#90]
## 🎉 Subtasks

- [ ] Eduardo to create summary of stakeholder research from Jonass
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@jessicazartler @cranders1

**Comment by eduardovegap** [comment]
Here is the link to the research folder: [Jonas research](https://drive.google.com/drive/folders/15rsKMaAb3cRlUoehhHGqFi3VyFXMQ0Xg ).

**Comment by GriffGreen** [comment]
Bad ass

**Comment by GriffGreen** [comment]
Is this closed @eduardovegap

**Comment by jessicazartler** [comment]
The summary turned into https://forum.tecommons.org/t/tec-funding-proposals-what-kinds-of-projects-should-apply/191

Not sure if there is anything else to glean out of it.. I think most of the valuable thoughts/insight were captured there.. I will have one more look back and see if there is anything else we could make out of it just in case, but I think that was most of it..
