### ISSUE TITLE
Forum post for CV's Alpha/Half Life

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#92]

**Comment by tamarandom** [comment]
Review check, please. ;) 

[https://docs.google.com/document/d/1_XpDFpRTSRKAMbC2YEKgjrE8VDHFgAiDFoTVkiNRWvI/edit](https://docs.google.com/document/d/1_XpDFpRTSRKAMbC2YEKgjrE8VDHFgAiDFoTVkiNRWvI/edit
)
